### PR TITLE
Replace index page verbiage with text-entry widgets and buttons

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Experimental branch with text-entry searches and buttons on the home page.

Flagging @That-Thing to review for technical and stylistic improvements, and others for content.

### CODE REVIEW

**Comment by That-Thing** [comment]
Looks good and readable, but it might be worth changing the default value of the search fields to be [placeholders](https://www.w3schools.com/tags/att_input_placeholder.asp) instead of actual text. This still gives users an idea of what can be searched for while not adding the minor annoyance of deleting the already present text if they wanted to search for something else.

current:
image
placeholder:
image

**Comment by StevenCannon-USDA** [comment]
@That-Thing - I experimented with the placeholder attribute (it was new to me), but reverted to the value= form since the placeholder also has its own minor annoyance I think: there seems to be no way to accept the example text. If you click on the example, it disappears. We could instead provide the example outside the text-entry box, as is done on the [gene search page](https://dev.soybase.org/tools/search/gene.html) - at the cost of another line under the text-entry box.

One other somewhat-significant change: the alert text at the top of the page takes up less real estate now.

**Review by maxglycine — APPROVED** [review]
I agree that not having to "remove" the text is good.  The example gives users the idea.  The other option would be to put the example text below the box so they could copy-n-paste an example into the box. Either solution is OK with me

**Comment by StevenCannon-USDA** [comment]
I think I'll go ahead and merge to main, but I don't think we are done with this home page.
We'll probably want to change what is included as buttons, improve the rollover text, etc.
The buttons themselves are also pretty simple/crude. @That-Thing - is there a way to fix the width of the colored portions of the button, so they don't look ragged?
Further changes can be made in other branches.

**Comment by That-Thing** [comment]
Adding a `width: 100%` style to both the uk-button div and the button element will make all the buttons the same length.

**Pull request merged**
