### PR TITLE
Expression page contrast

### LINKED ISSUE #163: Gene Expression Resources Page -- Text needs to be Black
The Gene Expression Resources for Soybean page (https://dev.soybase.org/tools/expression/) text needs to have the font color changed for contrast reasons.  The text should be Black, not Grey, for section 508 compliance.  I know I sent this out by email, but I figured that there should be an issue for it so it did not get forgotten.  It looks like the font-color was intentionally overridden by a local CSS section.  So just dropping the font-color in the CSS section may do it.

@StevenCannon-USDA @jd-campbell @ChenProm-USDA

### PR DESCRIPTION
**Pull request by ChenProm-USDA**
Expression Page:
* Update expression page font color to black for 508 compliance.

Main navigation bar:
* Update navigation font color to black for 508 compliance. 
* Fix issue with that prevents using keyboard to navigate through drop down.
  * Now you can tab to drop down and use up and down arrow to highlight child node and 'enter' to select node.
* add hovering effect to nav elements

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
This all looks good to me. I'll just comment for now and will leave the review & approval for Rex or Jacqueline.

**Comment by nathanweeks** [comment]
Naive question: is any of the coloring defined in the theme's [uikit-theme.css](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/assets/css/uikit-theme.scss) (such that it can be overridden in [_sass/variables.scss](https://github.com/soybase/jekyll-soybase/blob/main/_sass/variables.scss) -- I think?)

**Review by jd-campbell — APPROVED** [review]
I approve. Great work @ChenProm-USDA. I will not merge until Nathan's question in the PR has answered.

**Review by maxglycine — APPROVED** [review]
Looks great to me

**Comment by ChenProm-USDA** [comment]
> Naive question: is any of the coloring defined in the theme's [uikit-theme.css](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/assets/css/uikit-theme.scss) (such that it can be overridden in [_sass/variables.scss](https://github.com/soybase/jekyll-soybase/blob/main/_sass/variables.scss) -- I think?)

@nathanweeks I can look into it.

**Comment by StevenCannon-USDA** [comment]
It looks good to me too -- but to @nathanweeks' question, have a look at _config.yml, in this block:
```
# UIkit theme customization (sets site colors)
style:
  primary_background: '#235626' # Very dark green: '#296e01'
  global_muted_color: '#006600'
  invert_navbar_text: true
```
I am not sure how those interact with `_sass/*`, but the documentation in that section and _includes at https://github.com/legumeinfo/jekyll-theme-legumeinfo may help.

**Comment by nathanweeks** [comment]
It seems configuring UIKit via _config.yml was [deprecated in favor of the Sass approach](https://github.com/legumeinfo/jekyll-theme-legumeinfo/commit/51965415ab820f74765b8a205c673671f1fd62bc).

**Comment by maxglycine** [comment]
I don't get it.  What is the status of this PR?  I OK'ed it and so did Jackie.  What else needs to be done
@ChenProm-USDA @nathanweeks @jd-campbell @StevenCannon-USDA

**Comment by StevenCannon-USDA** [comment]
> I don't get it. What is the status of this PR? I OK'ed it and so did Jackie. What else needs to be done @ChenProm-USDA @nathanweeks @jd-campbell @StevenCannon-USDA

I think @ChenProm-USDA is looking again at the method. It looks like `variables.sass` is the preferred way to set font characteristics. See "details" for _sass at https://github.com/legumeinfo/jekyll-theme-legumeinfo.

**Comment by ChenProm-USDA** [comment]
> > I don't get it. What is the status of this PR? I OK'ed it and so did Jackie. What else needs to be done @ChenProm-USDA @nathanweeks @jd-campbell @StevenCannon-USDA
> 
> I think @ChenProm-USDA is looking again at the method. It looks like `variables.sass` is the preferred way to set font characteristics. See "details" for _sass at https://github.com/legumeinfo/jekyll-theme-legumeinfo.

Yes I'm looking into changing the global font color instead of individual pages/components.  I think I just found the correct variable to add to the variables.scss file to accomplish this.  I'm in the process of making the changes/testing now.

**Comment by ChenProm-USDA** [comment]
I added a global variable for text to be black.  This should make all main text black.  I was able to remove custom styling that forced font color to be black from various elements because of this.


I also updated the inputs used as buttons on the expression page to use the 'button' tag.  This gives them button behavior without having to use custom css.  All components should be updated to this change.

**Review by StevenCannon-USDA — APPROVED** [review]
This all looks good to me. And the implementation looks cleaner. I'll go ahead and merge. If other changes are needed, those can be handled in another branch down the road.

**Pull request merged**
