### PR TITLE
Makefile OS update and marker collection renaming

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Update datastore-metadata submodule and tools/translate/index.html to reflect renaming of collection s/glyma.Wm82_ISU01.gnm2/glyma.Wm82.gnm6/, and update CommandLineTools to macosx15.0 in Makefile.

To test, first do
```
  git submodule update --remote _data/datastore-metadata
```
To test the updated track in jbrowse, do
```
  make jbrowse
```

Flagging @nathanweeks to check the Makefile, @jd-campbell to check the data update, and @ChenProm-USDA in case of conflicts with soybase-audit-2

### CODE REVIEW

**Comment by nathanweeks** [comment]
Makefile looks OK (as long as the relevant symlink is created if needed via `sudo ln -s universal-darwin24 /Library/Developer/CommandLineTools/SDKs/MacOSX15.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin23`)

**Comment by StevenCannon-USDA** [comment]
Thanks for the review, @nathanweeks. I have added instructions for installation on MacOS.

**Comment by StevenCannon-USDA** [comment]
I have converted this to draft in order to fix some broken links.

**Comment by StevenCannon-USDA** [comment]
I believe I have fixed all of the reported broken links. Some were required changes in `Glycine/[species]/about_this_collection/description_Glycine_[species].yml`, so to test, first do
`git submodule update --remote _data/datastore-metadata`

Tagging @ChenProm-USDA, @jd-campbell, and @nathanweeks -- if one of you could review and approve, please (unless you find something that needs fixing). I'd like to get these fixes into production.

**Comment by nathanweeks** [comment]
The check-links job was erroneously reporting "success" on failure---fixed, revealing one more broken link.

**Comment by StevenCannon-USDA** [comment]
Thanks for the patch, Nathan. I have fixed that broken link; ready for re-review I think.

**Review by nathanweeks — APPROVED** [review]

**Pull request merged**
