### PR TITLE
add Wang_Duan_2024 transcription tracks to JBrowse

### PR DESCRIPTION
**Pull request by weihuang12**

### CODE REVIEW

**Review by maxglycine — CHANGES_REQUESTED** [review]
Wei:  This is great.  A lot of work.  The only issue I have is that there is no way to get to the Wang_Duan_2024 collection report or a link to the paper.  Without that the user is left with trying to figure out where the data is from.  Can you make a link in the popup window  that goes to either the paper (DOI) or the paper record in the mine? @weihuang12 @jd-campbell @StevenCannon-USDA @ChenProm-USDA

**Comment by StevenCannon-USDA** [comment]
> Can you make a link in the popup window that goes to either the paper (DOI) or the paper record in the mine? 

It looks like the available options for this are:

1. put the DOI  in the `config.description`, which is seen when you click on the three dots to the left of the track, then "About track"; or 
2. put the DOI (or other parts of the citation) into a column-9 attribute for each feature.

I really dislike option 2, as it would be super-redundant and would set a bad precedent relative to other GFFs. So, that leaves option 1 - unless there are other approaches that @nathanweeks or @weihuang12 know of.

Here is the preprint citation:
```
Widespread transcription initiation within coding sequences marks tissue identity and accessible chromatin
Xutong Wang, Jingbo Duan, Chancelor B. Clark, Wanjie Feng, Jianxin Ma
bioRxiv 2024.03.27.587116; doi: https://doi.org/10.1101/2024.03.27.587116
```

**Comment by maxglycine** [comment]
I would vote for #1 also.  Keeping in mind that there is also the option to link to the GlycineMine report for Wang_Duan_2024.  Which ever is easier to execute will be fine.

**Comment by weihuang12** [comment]
@nathanweeks , can we add DOI link of the paper in the description part of the MANIFEST*.yml, since the jbrowse-tracks.sh
script parses the description from this yaml file?

**Comment by nathanweeks** [comment]
Would a link to the README (or directory containing the README) work (e.g., `more info: <URL>` appended to the track description)?

**Comment by StevenCannon-USDA** [comment]
> Would a link to the README (or directory containing the README) work (e.g., `more info: <URL>` appended to the track description)?

That sounds like a good idea to me. It would allow people to find the underlying data, and the README will be most reliably updated -- for example, when the main paper is published and replaces the preprint.

**Review by maxglycine — APPROVED** [review]
If a link can be made to either the readme page that will be fine

**Comment by nathanweeks** [comment]
Done. Alternatively, the README could be embedded in the File Info section (as is done with with the Reference sequence tracks), though it would replace any existing track metadata (e.g., GFF or VCF headers).

**Pull request merged**
