### PR TITLE
October 1 News iteam

### PR DESCRIPTION
**Pull request by jd-campbell**
I made a new October 1st news item.

### CODE REVIEW

**Comment by nathanweeks** [comment]
Minor suggestion: for internal links, using relative URLs  (`<a href="/about/"...`) can make testing easier. Not sure if `target="_blank"` is necessary for an internal URL in this case, but either way it's not a big deal.

**Review by StevenCannon-USDA — COMMENTED** [review]
Thanks for preparing this announcement. Here is an alternative candidate, aiming at correcting some errors and awkwardness:

```
As of October 1, 2024, SoyBase has transitioned to a new design and set of web and database methods. 
The changes are to improve the user experience and to help incorporate greatly expanded genomic data. 
If you have any questions or find problems with this new version, please let us know using 
the site <a href="/about/"> contact form</a>.

The Legacy SoyBase website will also remain accessible using 
the URL <a href="https://legacy.soybase.org/">legacy.soybase.org</a>.
```

**Comment by jd-campbell** [comment]
@StevenCannon-USDA 
Thank you for the alternative candidate. My short news post was a very rough draft.  Please review again.

**Review by StevenCannon-USDA — APPROVED** [review]
Looks fine to me.

**Pull request merged**
