### PR TITLE
Trait linkouts

### PR DESCRIPTION
**Pull request by adf-ncgr**
this uses a new version (v1.1.0) of the theme, plus some small modifications to the trait.html to enable linkout functionalities for the trait search component (the soybase graphql server instance has been updated to include linkouts, so I hope everything here should "just work", but feel free to let me know if not or to make changes as you see fit.

### CODE REVIEW

**Review by That-Thing — APPROVED** [review]
Works for me.

**Review by StevenCannon-USDA — COMMENTED** [review]
For me testing locally this morning ("make" and localhost on laptop), I am seeing an error "Failed to load data" for both "Gene search" and "Trait Association Search"

**Comment by adf-ncgr** [comment]
@StevenCannon-USDA can you look at the dev console in the browser and see what errors are reported there? I'm not able to reproduce what you're seeing.

**Comment by StevenCannon-USDA** [comment]
> @StevenCannon-USDA can you look at the dev console in the browser and see what errors are reported there? I'm not able to reproduce what you're seeing.

Uncaught (in promise) Error: No form data function provided

Uncaught SyntaxError: The requested module 'lis-graphql' does not provide an export named 'traitAllModalLinksFactory' (at trait.html:572:7)

I'll add: I realized that I hadn't done `git submodule update --recursive` ... but after doing that, the error remains.

**Comment by adf-ncgr** [comment]
Thanks @StevenCannon-USDA. I think the first one is ignorable, something that @alancleary tells me is an innocuous (but confusing) bug that has to do with timing but doesn't actually affect anything. The second one is where the issue is. I think it has to do with you not having gotten the right version of the theme submodule; you probably just need to checkout the branch using --recurse-submodules or by some equivalent method to ensure that the submodule gets the version that the traits_linkout branch uses (I'm no expert in the use of submodules, but I find using --recurse-submodules when switching branches via checkout does the trick)

**Comment by alancleary** [comment]
If the submodule update @adf-ncgr suggested doesn't work, try removing your local `_site/` directory before building the site.

**Comment by StevenCannon-USDA** [comment]
@adf-ncgr and @alancleary - thanks, but no luck so far. I cleared out _site (actually did `make clean` with was probably overkill), then 
```
git checkout trait_linkouts --recurse-submodules
git status
  On branch trait_linkouts
  Your branch is up to date with 'origin/trait_linkouts'.
```

Checking the web components code to see if I have the right version:
```
grep -n traitAllModalLinksFactory _themes/jekyll-theme-legumeinfo/assets/js/graphql/get-traits.js
202:export function traitAllModalLinksFactory(modalId) {

wc ~/proj/24/sbj/jekyll-soybase/_themes/jekyll-theme-legumeinfo/assets/js/graphql/get-traits.js
     207     802    7068 _themes/jekyll-theme-legumeinfo/assets/js/graphql/get-traits.js

ls -l ~/proj/24/sbj/jekyll-soybase/_themes/jekyll-theme-legumeinfo/assets/js/graphql/
total 120
-rw-r--r--  1 stevencannon  staff   9173 Apr 10 09:57 get-genes.js
-rw-r--r--  1 stevencannon  staff  13547 Apr 10 09:57 get-linkouts.js
-rw-r--r--  1 stevencannon  staff   3729 Feb 27 10:32 get-organisms.js
-rw-r--r--  1 stevencannon  staff   2864 Apr 10 09:57 get-publications.js
-rw-r--r--  1 stevencannon  staff   3355 Apr 10 09:57 get-qtls.js
-rw-r--r--  1 stevencannon  staff   7068 Apr 10 09:57 get-traits.js
-rw-r--r--  1 stevencannon  staff    262 Apr 10 09:57 index.js
-rw-r--r--  1 stevencannon  staff    906 Jan 25 13:05 modal.js
-rw-r--r--  1 stevencannon  staff   1031 Feb 27 10:32 query.js
```

**Comment by alancleary** [comment]
@StevenCannon-USDA Did you clear your web browser's cache?

**Comment by StevenCannon-USDA** [comment]
> @StevenCannon-USDA Did you clear your web browser's cache?

D'oh! That was it. Thanks. 

Works beautifully. I will approve and merge.

**Review by StevenCannon-USDA — APPROVED** [review]

**Comment by adf-ncgr** [comment]
Great, thanks for taking it through the last steps- amazing how many ways things can go wrong!

**Pull request merged**
