### PR TITLE
Legacy redirects

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
- Made a legacy_urls page in help/ (this seems preferable to community/, since people are likely to be looking for help if they can't find something ... and the sitemap is also currently in help/)
- Added hints and links to 404.html
- Added a link to the nust site in the tools page
- Added anchors to the tools page to permit linking to the search section
- Nathan added the jekyll-redirect-from plugin, and added those redirects to the relevant pages.

### CODE REVIEW

**Comment by nathanweeks** [comment]
Might be helpful to sort the list in the legacy_url's page by legacy_url?

**Review by maxglycine — COMMENTED** [review]
I was unable to trigger the redirect from the codespace version.  I tried legacy.soybase.org/projects/SoyBase.C2020.02.php%22 directly and it did go to a 404 with the explanations you put in it so that part was good.  I just don't know how to evaluate the rest
@StevenCannon-USDA @jd-campbell

**Comment by StevenCannon-USDA** [comment]
> Might be helpful to sort the list in the legacy_url's page by legacy_url?

Thanks for the suggestion. I have added that sorting.

**Review by maxglycine — APPROVED** [review]
OK, I finally found where this mythical "Redirect" Page was.  I don't remember saying we would put it in the "About & Contact" page.  The last we talked the link to the "Legacy URLs" was going in the "Community" page.  Putting it in the "About" page is no more opaque than the "Community" page, I guess.  
@StevenCannon-USDA @jd-campbell

**Pull request merged**
