### PR TITLE
Pangene lookup

### PR DESCRIPTION
**Pull request by ChenProm-USDA**
Add Pangene Lookup component to tools/translate/index.html

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
It looks like this branch derived from an older SBW branch. It includes images in `assets/img/sbw`, which have since moved to the datastore annex.
But the content and function at `/tools/translate/` looks good to me. After the extraneous images are removed, I'll approve for merging.

**Comment by nathanweeks** [comment]
I think the assets/js/graphql files are in the theme:

https://github.com/legumeinfo/jekyll-theme-legumeinfo/tree/main/assets/js/graphql

Would probably want to update the theme submodule instead of copying the js files into assets/js, as they would eventually become out-of-date?

**Comment by ChenProm-USDA** [comment]
Made the changes requested.  I updated to the latest theme and removed graphql folder from assets.  Also removed the old sbw img folder.

**Comment by StevenCannon-USDA** [comment]
> Made the changes requested. I updated to the latest theme and removed graphql folder from assets. Also removed the old sbw img folder.

The new changes look good to me, but now I am seeing "Failed to load data" at the top of the web component. This is in my local test (with "make" on my M2 Mac).

EDIT: Never mind. I hadn't updated the theme. It's working fine for me now.

**Review by StevenCannon-USDA — APPROVED** [review]
Looks good after the latest changes.

**Pull request merged**
