### PR TITLE
Scannon

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
New content under about and resources (genome_info and iframes to dscensor)

### CODE REVIEW

**Review by maxglycine — COMMENTED** [review]
I think you should be explicit so how about 👍 
"and genomic data accessions at the major genomic data repositories: GenBank, EMBL, DDBJ and variant data at the European Variation Archive (EVA)"

**Comment by jd-campbell** [comment]
@StevenCannon-USDA did you still need a review of this branch?

**Comment by maxglycine** [comment]
Your branch will not run in codespaces so I can’t really see what you did. One of the drawbacks of relying on liquid to render.

**Comment by StevenCannon-USDA** [comment]
> @StevenCannon-USDA did you still need a review of this branch?

@jd-campbell No thanks. There's more that I'd like to do. I have switched this branch to "draft" status.

**Comment by StevenCannon-USDA** [comment]
Quite a few items for review, please:
- Under GENOMICS (/resources), new text in the overview section, including a link to ...
- ... a new page /resources/genome_info/ , with content from https://soybase.org/genome_assemblies.php
- Fixed all remaining broken links (I think; we'll see if anything new crops up)
- At /about , added a link to about/soybase_about/index.html
- Some minor table-styling changes at about/lgs_and_chromosomes/index.html

**Review by maxglycine — APPROVED** [review]
Looks good as code.  Thanks.

**Review by maxglycine — APPROVED** [review]
Looks good to me.

**Pull request merged**
