### PR TITLE
added Soybean Breeders Workshop imgs

### PR DESCRIPTION
**Pull request by jd-campbell**
I need to add the images to main because I need these images for multiple branches I am working on.

### CODE REVIEW

**Comment by nathanweeks** [comment]
The three personnel pics would increase the size of the git repo (main branch) by about ~25%. Could those be linked to from other public/official sources? The hotel PDF might not be needed as an asset for building the core site; perhaps it could be sourced from a file-hosting service (like Box)?

**Comment by StevenCannon-USDA** [comment]
How about in a subdirectory in /usr/local/www/data/annex/Glycine/max/meetings

**Comment by nathanweeks** [comment]
e.g.:
https://plantpathology.ca.uky.edu/sites/plantpathology.ca.uky.edu/files/bradley_carl_2015.jpg
https://plpa.cfans.umn.edu/sites/plpa.cfans.umn.edu/files/styles/cfans_profile_photo/public/2020-07/cory_hirsch.jpg
https://phytobiomesalliance.org/wp-content/uploads/2020/02/Jan_Leach.jpg

**Comment by jd-campbell** [comment]
I am closing this PR.

**Pull request closed without merging**
