### PR TITLE
Font tweaks

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Change font color for links in left-hand tools menu (from light gray to dark green). Uses scss files to override defaults: https://github.com/legumeinfo/jekyll-theme-legumeinfo/tree/uikit-updates#_sass

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
@nathanweeks - It is possible that the submodule conflicts have been resolved in a new commit, after the initial PR. But I still have a shaky understanding of how deal with the submodules. Fwiw, I did the following:
```
git submodule update --remote _themes/jekyll-theme-legumeinfo
git commit -m 'update theme submodule'
git commit -m 'update theme submodule' _themes/jekyll-theme-legumeinfo

git submodule update --remote _data/datastore-metadata
git commit -m 'update datastore-metadata submodule' 
git commit -m 'update datastore-metadata submodule' _data/datastore-metadata
```

**Comment by nathanweeks** [comment]
GitHub still shows merge conflicts. The font-tweaks branch was branched from 16cd186ba68d7c5b41cf034c25c09982507b2dc8 (committed to main on January 5), and a commit e5786f81f46cb875e137044224156c87ef52b3b9 (merged on January 8) modified the submodules in the interim. Following the commands suggested in the "Use the command line" link should help resolve the merge conflict. Branching from the most-recent commit on the main branch could help avoid this scenario in the future.

**Comment by StevenCannon-USDA** [comment]
Thanks @nathanweeks. It looks like the command-line merge did the trick.

**Review by jd-campbell — APPROVED** [review]
Reviewed during GitHub meeting. Ok by Rex. Approved to merge.

**Pull request merged**
