### PR TITLE
Responsive page

### PR DESCRIPTION
**Pull request by ChenProm-USDA**
* **Global**
    * Add global variable to handle black text color. 
* **Homepage** 
    * Main content located in the center of the page uses tables and is not responsive.  When the window becomes smaller a horizontal scroll bar is rendered. 
    Fix:
    * Utilize Flexbox and Grid layouts
    *  Create custom media queries to handle element colors
    * Blog/News/Event cards located on the right side will disappear and become inaccessible between 639px - 1200px.
        * Implement CSS to render Blog/News/Event cards below main content when screen is smaller than 1200px.
        * Write custom logic to render upcoming events. (unable to import event_card directly from source component.  When doing this it will break events_card in right side cards.
    * Update buttons utilize UI kit button classes.
   
Screenshot 2024-09-18 at 16 30 42
Screenshot 2024-09-18 at 16 45 26
Screenshot 2024-09-18 at 16 39 29

* **Expression Page**
    * Divide different components into cards
    * Update buttons with Ui kit button classes
    * Update inputs with Ui kit input classes
    * Incorporate mobile responsiveness using UI kit classes
    
Screenshot 2024-09-18 at 16 38 22

* **SoySNP50K Page**
    * Incorporate mobile responsiveness using UI kit classes.
        * Center bottom table on smaller devices.
        * Add horizontal scrollbar to table for smaller screens.
* **Go Analysis Page**
    *  Incorporate mobile responsiveness using UI kit classes.
        * Element will be centered on smaller screens.
    * Update buttons with Ui kit button classes
    * Create functions to handle disabling buttons if text area is empty or no file has been selected in upload text component.
    
Screenshot 2024-09-18 at 16 43 06

* **Gene-name translator**
    * Add horizontal scrollbar to table for smaller screens
* **Cmap-js: Genetic Map Viewer**
    * Fix all accordion being open instead of just the first one under "…new CMap-js viewer" portion.
    * Add horizontal scroll to table for smaller scree

Screenshot 2024-09-18 at 16 47 04

### CODE REVIEW

**Review by maxglycine — APPROVED** [review]
Chen:

The pages look great.  They are now truly responsive.
You are a rock star!

**Comment by StevenCannon-USDA** [comment]
I agree - very nice work, @ChenProm-USDA.
Some minor things that I'd like to see if they could be addressed easily -

It looks like the bottom row of buttons didn't make it into this PR: 
[Other Legumes] [Expression Resources] [Help & Contact]

The GO buttons: good that those are now standard uikit, but the dark green stands out visually as the most prominent feature in the page. Is it possible to set a lighter color for the buttons (home page and expression)?

**Comment by maxglycine** [comment]
@StevenCannon-USDA  Remember the 508 compliance issue is to have as high a contrast as possible in the text.  If you lighten the "Green" you also reduce the contrast.  If you make the buttons lighter, then we may want to change the text color to Black to get the contrast.  Currently, the "Active" buttons have a dark green background and the inactive buttons have a white background.  This is to make it clear which buttons are active.  Lightening the green would reduce the contrast between active and inactive  buttons.  Yes, the eye is drawn to the green buttons, but that is on purpose.  If I had reduced vision I would probably like the higher contrast between buttons.  I don't think we should change it.

**Comment by ChenProm-USDA** [comment]
@StevenCannon-USDA
Fixed: "It looks like the bottom row of buttons didn't make it into this PR:
[Other Legumes] [Expression Resources] [Help & Contact]"

**Review by StevenCannon-USDA — APPROVED** [review]
Many improvements. Nice work.

**Pull request merged**
