### PR TITLE
Change left tool bar links

### PR DESCRIPTION
**Pull request by jd-campbell**
I changed the LIS Germplasm GIS Viewer and ConeKet links to that they lead to Glycine view for both tools.

### CODE REVIEW

**Review by maxglycine — CHANGES_REQUESTED** [review]
The page that you have Coneket going to is not very informative.  It is not a search page and it is not a tools page.  It does not give any indication of what to do or what Coneket can provide.  It would be best if the link took you to this page:

Screenshot 2024-06-21 at 8 03 53 AM

You may have to ask @adf-ncgr how to do it.
@jd-campbell @StevenCannon-USDA

**Comment by adf-ncgr** [comment]
FWIW, the URL for that page is: https://conekt.legumeinfo.org/features

**Comment by StevenCannon-USDA** [comment]
> FWIW, the URL for that page is: https://conekt.legumeinfo.org/features

Thanks, @adf-ncgr . Weirdly, I wasn't able to find that page via the menus (though I was probably missing something obvious).

Maybe a question for @sdash-github: a natural tool to link to (if we have to choose one) would be https://conekt.legumeinfo.org/heatmap/. Following the example (Phaseolus genes), I tried a collection of soybean genes:
```
glyma.Wm82.gnm4.ann1.Glyma.01G207300 glyma.Wm82.gnm4.ann1.Glyma.03G114300 glyma.Wm82.gnm4.ann1.Glyma.05G062700 glyma.Wm82.gnm4.ann1.Glyma.07G112400 glyma.Wm82.gnm4.ann1.Glyma.09G241800 glyma.Wm82.gnm4.ann1.Glyma.11G035900 glyma.Wm82.gnm4.ann1.Glyma.17G144700 glyma.Wm82.gnm4.ann1.Glyma.18G253800 
```
... but these result in `Internal Server Error`. Is the error in the list somehow, or in something in the conekt configuration?

**Comment by adf-ncgr** [comment]
@StevenCannon-USDA I think the issue with your soybean attempt is that we have glyma.Wm82.gnm2.ann1 as our annotations- hit the comparative tab and load that example and you'll see some soybean genes among those given. 

And yes, that tools pages is oddly difficult to find- not sure if that might have been something @sdash-github tried to hide because of some of the tools not being fully supported by the needed data?

**Comment by StevenCannon-USDA** [comment]
@adf-ncgr Thanks again; the problem was indeed the annotation version of my genes.
That raises the question: would it be possible to provide examples for each of the species? I know that it's out of scope to modify the Conekt  code, but maybe sample gene lists could be given in the introductory text on each page? Or even a dirty hack of providing sequences from all five species triggered by "Load example". My testing suggests this would work; the sequences from the "other" species seem to be ignored.

**Comment by sdash-github** [comment]
> > FWIW, the URL for that page is: https://conekt.legumeinfo.org/features
> 
> Thanks, @adf-ncgr . Weirdly, I wasn't able to find that page via the menus (though I was probably missing something obvious).
> 
> Maybe a question for @sdash-github: a natural tool to link to (if we have to choose one) would be https://conekt.legumeinfo.org/heatmap/. Following the example (Phaseolus genes), I tried a collection of soybean genes:
> 
> ```
> glyma.Wm82.gnm4.ann1.Glyma.01G207300 glyma.Wm82.gnm4.ann1.Glyma.03G114300 glyma.Wm82.gnm4.ann1.Glyma.05G062700 glyma.Wm82.gnm4.ann1.Glyma.07G112400 glyma.Wm82.gnm4.ann1.Glyma.09G241800 glyma.Wm82.gnm4.ann1.Glyma.11G035900 glyma.Wm82.gnm4.ann1.Glyma.17G144700 glyma.Wm82.gnm4.ann1.Glyma.18G253800 
> ```
> 
> ... but these result in `Internal Server Error`. Is the error in the list somehow, or in something in the conekt configuration?

1.  Conekt was built several years back when the most recent expression data available for Glyma was from  Wm82.gnm2.ann1. This is reflected in the page https://conekt.legumeinfo.org/species/view/2.  I generally providedhttps://conekt.legumeinfo.org/species/ as a link for a species to choose from.  

2. In the mean time our most recent genome/annotation versions have changed for almost all species and also the decision that we will no longer follow the expression computation pipeline that we followed in the past.  New expression data are being generated with NF Core RNASeq pipeline by Evan. I plan to re-build Conekt after the relevant expression datasets from our legume spp are vailable. Currently he is doing the Glycine datasets.  Until then we have decided not to do any improvements to the Conekt tool interface.  
3. We used the user interface of Conekt as such as we didn't want to get into modifying their code. As a result the UI is not the way want it to be and I ended up hiding some of the tools from the Menu, all funcationalities of Conekt are not being used by us anyway, e.g. expression network.  
4. Andrew and I have talked that the only way can make it more informative is by: 
     --  providing our-own-constructed landing page for Conekt where the genome-annotation ver info, other useful, etc. is provided along with links and what to expect, etc. 
    -- This I plan to do as a Jekyll page and can be customized for PB/LIS/SB with specific relevant info.
    -- I plan to do for our next Conekt build.
5. For now a I can create a generic Jekyll page page in LIS for the current build with some info that removes these confusions and ambiguities in Conekt and using Conekt.

Can we wait until I am back from APRES (mid-July)?  If there is some urgency I can spin a page quickly and will modify it later until the new built is available.  Please let me know: @StevenCannon-USDA ,  @adf-ncgr

**Comment by StevenCannon-USDA** [comment]
@sdash-github - that's all informative and helpful.
Considering those constraints and timelines, my feeling is that the link that @jd-campbell used in this PR is fine for now. It delivers people to the species page for Glycine. From there, a user can access other tools and help via the menu. Clicking on any of the genes gives an expression plot, e.g. https://conekt.legumeinfo.org/sequence/find_forLIS/glyma.Wm82.gnm2.ann1.Glyma.01G003800 
... and from there, a user who knows something about URLs should also be able to enter a particular gene of interest in the URL. (Not ideal in terms of UI, but workable).
What do you think, @maxglycine: OK to use the current species page for now?

That raises the idea, though: would it be reasonable, @adf-ncgr, to link to such pages via the linkout service?

**Comment by adf-ncgr** [comment]
> That raises the idea, though: would it be reasonable, @adf-ncgr, to link to such pages via the linkout service?

It's so reasonable that it was already implemented for soybean (can't recall who requested it); as long as it is a glyma.Wm82.gnm2.ann1 gene you should already see the link, but let me know if not.

**Comment by StevenCannon-USDA** [comment]
> It's so reasonable that it was already implemented for soybean

Cool! When your wishes are granted with preemptive telepathy.

**Review by StevenCannon-USDA — APPROVED** [review]
My vote is to approve as-is -- with the understanding that the link target might be reevaluated after updates to CoNekT later in the summer.

**Comment by maxglycine** [comment]
I am not sure where we are with this thread.  But I do want to point out that "you only get one chance to make a first impression".  When we go "live" everyone will not have seen this tool.  If we frustrate them almost immediately, they will not have a good impression of the site.  I would really try not to frustrate our users and therefore make all the tool links as expressive and useable as possible.  I have seen the CoNekT page before and still miss the the "Home" link at the very top of the page.  This leads you to a home page that does not really tell you anything useful.  You have to again look up at the top again to see the "Tools" link and click it to get an explanation of the tools functions and links to those functions. 

Clicking on one of the "glymas" in the current page does give you something but If you have a gene list. It does not really tell you how to use it.  You would have to see the "home" link to get to the "Home" page and then see the "Tools" link to start to get to some useful information on what the tool does and how to use your gene list.(Compare Profiles).  We should just cut to the chase and give them the "Functions" page first.

**Comment by StevenCannon-USDA** [comment]
Reporting a plan that @maxglycine and I hatched (by phone just now): Rex will work on a dedicated landing page for Jekyll-SoyBase that introduces the available functionality, similar to the suggesion from @sdash-github bullet 4 above. We think that at least for the single-gene display, an input field can be used to drive a search, similar to what we're doing on the site home page for the mine keyword search and the gene search, e.g.
https://conekt.legumeinfo.org/sequence/find_forLIS/glyma.Wm82.gnm2.ann1.Glyma.01G207300

**Comment by sdash-github** [comment]
To @maxglycine and @StevenCannon-USDA :  
I do see the point about first impression by users and appreciate it too. 
Therefore, for a quick (for the time being only) workable modification of the Conekt home page  (https://conekt.legumeinfo.org/) please suggest a few lines of text that you would like to see that would take you to the links at Conekt and provide some clarity to the users.  

Requesting the following:
1. Please suggest a few lines generic texts for all legumes and then,
2. specific lines of text for other legumes and the links. 
3.  This will reduce the amount of work from me right away as I am focussing on a cnference prep. 
4. The idea here is to provide the links from LIS/PB/SB (left panel and tools) to Conekt home page which will serve as the landing and direct users to **only** the species and tools we have along with some helpful hints/info like genome/annot versions and others as you see fit. 

If you give me the html text that will be great and THEN I will quickly modify the home page as landing and basecamp page with some help from  @adf-ncgr

**Comment by StevenCannon-USDA** [comment]
Checking about the status of this branch. I think we don't want this to fall too far down in the task list.

**Comment by sdash-github** [comment]
I am now back from APRES and after @maxglycine provides/suggests the text and links, I can incorporate them.

**Pull request closed without merging**
