### PR TITLE
Add legacy tool links

### PR DESCRIPTION
**Pull request by jd-campbell**
Many SoyBase stakeholders are asking for tools that are not on Jekyll SoyBase. I did the following things on this branch on the tools.yml file: 

- Added Legacy Tools category
- Added GRIN Data Explorer link 
- Added Expression Explorer link 

Please review. I have also add these two tools to the project plan for 1.1.

### CODE REVIEW

**Comment by maxglycine** [comment]
It looks good to me @jd-campbell.  I tried to find a way to "review" it but I did not see a way

**Review by StevenCannon-USDA — COMMENTED** [review]
Minor yaml error (trailing spaces) on lines 93 and 101

**Review by StevenCannon-USDA — COMMENTED** [review]
I notice that those links are also at https://www.soybase.org/about/legacy_urls/ ... but descriptions could be added in the section "See this content at". Would need to add that key-value group to legacy_urls.yml and change the liquid accordingly. Maybe handle in a separate PR later.

**Comment by jd-campbell** [comment]
> Minor yaml error (trailing spaces) on lines 93 and 101

@StevenCannon-USDA  -- fixed

**Review by StevenCannon-USDA — APPROVED** [review]

**Pull request merged**
