### PR TITLE
Parentage page

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Parentage page (tools/parentage/) now links to a page with code prefix descriptions, and the data submission template and bulk data file are linked.

### CODE REVIEW

**Comment by jd-campbell** [comment]
I have reviewed and it looks good. Thank you for your work.

**Comment by StevenCannon-USDA** [comment]
@jd-campbell - thanks for the review - but I don't think the branch was merged to main. Reopening. To merge, the PR needs to be approved (view the files, then review and approve if appropriate).

**Comment by StevenCannon-USDA** [comment]
Pinging @jd-campbell or @maxglycine - I'd like to finish this PR and merge to main if it is at an acceptable stage. We can make further changes later, but I think it's good to close issues and keep pushing ahead when possible.

**Comment by maxglycine** [comment]
I believe @jd-campbell gave you the ok last week

**Comment by StevenCannon-USDA** [comment]
The thing is: a comment on the PR isn't sufficient. Review and approval is needed.  One way is to click "Files changed", then the green "Review changes" button, then the "Approve" radio button if appropriate.

**Review by maxglycine — APPROVED** [review]
Have OK'ed it

**Pull request merged**
