### PR TITLE
Merge separate project YAML files into one & make CI faster

### PR DESCRIPTION
**Pull request by nathanweeks**
Make CI jobs `build` faster (by caching jbrowse build) and `pa11y` faster (by increasing concurrency).

Merge separate project YAML files into a single projects.yml.

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
Looks good to me, though I note that the changes in last week's "responsive" branch aren't reflected in this branch.

**Review by maxglycine — COMMENTED** [review]
Well, I believe you that it was needed.  Does this change Steven's protocols in any way? Should we determine that before we merge? Does this request also bear on the gene-registry YAML file? @StevenCannon-USDA @jd-campbell

**Comment by StevenCannon-USDA** [comment]
> Well, I believe you that it was needed. Does this change Steven's protocols in any way? Should we determine that before we merge? @StevenCannon-USDA @jd-campbell

No change in protocols (for adding project pages). Just a restructuring of the data within Jekyll.

**Comment by maxglycine** [comment]
@StevenCannon-USDA Doesn't your protocol specify how to make a separate YAML file for each "project"?  Also the protocol for processing a new gene for the gene registry specifies making a separate YAML document for each paper, doesn't it? @jd-campbell @nathanweeks.

**Comment by nathanweeks** [comment]
> Looks good to me, though I note that the changes in last week's "responsive" branch aren't reflected in this branch.

`main` was merged, and this branch looks up to date. Did something break, or is your local branch behind?

**Comment by StevenCannon-USDA** [comment]
> `main` was merged, and this branch looks up to date. Did something break, or is your local branch behind?

Oops, you are right. My `main` must have been out of date. It all looks correct to me now. Approving ...

**Review by StevenCannon-USDA — APPROVED** [review]

**Comment by StevenCannon-USDA** [comment]
> Doesn't your protocol specify how to make a separate YAML file for each "project"?

@maxglycine - We don't actually have a written protocol yet for adding projects. Just the Jekyll patterns in the data file, and the liquid code in _layouts/projects.html. Would be good to write up some instructions, but we haven't done that yet.

The gene family registry -- we are curating into separate yaml files per study just to make the curation & review process manageable. But that's independent of projects.

**Pull request merged**
