### PR TITLE
Links open in new tabs

### PR DESCRIPTION
**Pull request by ChenProm-USDA**
- tools.yml
  - add new key value pair, target: "_blank".  Use to decide if link should be open in a new tab.  This will render in <a/> tag as 
an attribute's value.

- root _includes folder
  - add tools.menu.html to folder.  This is used to control the links in the left side Tool menu.
    - add target={{item.target}} to <a/> tag, which is pulls the from tools.yml.

- index.html (middle of the page links on home page)
  -  hard coded  target="_blank" to links that needed to open in new tab.

- tools/index.html and includes/navbar-menu-items.html
   - add target={{item.target}} to <a/> tag, which is pulls the from tools.yml.

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
This implementation looks good to me, but I suggest these changes:

Remove target=_blank, since these all have navigation that returns a user to soybase.org:
-   Datastore
-   SequenceServer
-   Genome Context Viewer

  
Remove link from nav and from tools page (since it is now handled by the Gene Search component):
-   Gene Family Search

**Comment by ChenProm-USDA** [comment]
@StevenCannon-USDA Changes made.  Please review.  Thanks.

**Review by StevenCannon-USDA — APPROVED** [review]
Looks good

**Comment by maxglycine** [comment]
Remove target=_blank, since these all have navigation that returns a user to soybase.org:

    Datastore -- yes if you click on the soybase logo at the top of the page, but it currently goes to soybase.org which is Ok now, but will have to be changed when dev goes "live"

SequenceServer -- yes, if you click on the soybase logo at the top of the page, it does take you back to the dev home page which is good and will not have to be changed when dev goes "live"

Genome Context Viewer -- yes if you click on the soybase logo at the top of the page, but it currently goes to soybase.org which is Ok now, but will have to be changed when dev goes "live"

@StevenCannon-USDA @jd-campbell

**Comment by StevenCannon-USDA** [comment]
@maxglycine - after the rollover on Oct 1, clicking on the favicon at `https://data.soybase.org` will take the user to `https://www.soybase.org` ... which will be the content that is currently at `https://dev.soybase.org` That is the desired behavior, no?

**Comment by maxglycine** [comment]
Yes for the flavacons on the datastore and context viewer that is correct.  but for the sequenceserver it will take you dev.soybase.org which will probably redirect to soybase.org, but that is not the way to do it.  The way to do it is to change the URL under the flavacon to go to soybase.org not dev.soybase.org.  No?

**Comment by StevenCannon-USDA** [comment]
After a Zoom session with Rex, I understand the question. I think I know the answer, but I am not sure. So, asking @ChenProm-USDA or @nathanweeks:
At the time that the Jekyll site is made live (meaning, soybase.org gets pointed to that content), what will be the behavior of the favicon link in the nav bar? Right now, it takes the user to the home page, https://dev.soybase.org. After rollover, will it take the user to the home page ... which will be https://soybase.org? In other words, it goes "here" in both cases -- whatever "here" happens to be?

**Comment by nathanweeks** [comment]
Right. Inspecting the element in a web browser: `<a class="uk-navbar-item uk-logo uk-text-truncate" href="/">...`

**Pull request merged**
