### PR TITLE
Enable JBrowse tracklist by default

### LINKED ISSUE #117: JBrowse: Add feature
When a user opens a JBrowse on dev.soybase.org the available track box is not visible on the screen.  Is there a setting or config to make the available track box to just show up automatically? 

As it is now the user just has to know to click on the "three lines" and select track selector on the drop down list.

### PR DESCRIPTION
**Pull request by nathanweeks**
Fixes #117 

Requires JBrowse version bump to fix https://github.com/GMOD/jbrowse-components/pull/4250

### CODE REVIEW

**Review by jd-campbell — COMMENTED** [review]
Thank you for working on this so quickly. 
I opened a codespace on the jbrowse-tracklist branch to view the JBrowse track list box. I tested out about 10 different Glycine genomes, but I get a 404 error for all the links I tested.  I have attached a screen shot. 


Screen Shot 2024-03-28 at 08 28 54

**Comment by nathanweeks** [comment]
Was `make jbrowse` executed before `make`?

**Comment by maxglycine** [comment]
@nathan  @jd-campbell I did make jbrowse and then make and it does appear to work.  I picked the Wm82.a2 Gm01 jbrowse link. But there is a thing.  In the browser that is integrated, the link to jbrowse did not work for me.  If I copied the URL and then went to FF and pasted the URL in it, Jbrowse came up and the track picker box was open and had a bunch of tracks  to choose from.

**Review by maxglycine — APPROVED** [review]
Looks good to me

**Comment by nathanweeks** [comment]
> @nathan @jd-campbell I did make jbrowse and then make and it does appear to work. I picked the Wm82.a2 Gm01 jbrowse link. But there is a thing. In the browser that is integrated, the link to jbrowse did not work for me. If I copied the URL and then went to FF and pasted the URL in it, Jbrowse came up and the track picker box was open and had a bunch of tracks to choose from.

It is definitely more reliable to use a real browser tab if rendering any javascript-heavy content. For convenience, one can click the box with the arrow in the top-right corner of the simple browser view to open the page in a new tab.

**Pull request merged**
