### PR TITLE
Accessibility tests (pa11y)

### PR DESCRIPTION
**Pull request by nathanweeks**
Provides a baseline automated accessibility testing configuration/results via a "pa11y" makefile target (`make pa11y`) & GA workflow job (currently for informational purposes only, as with link checking).

### CODE REVIEW

**Review by StevenCannon-USDA — APPROVED** [review]
As far as I can tell, it works fine (tested on a local server, with M1). I see the sitemap.xml.

A tangential question: What should our practice be when we see notification of submodule changes in a branch? E.g.,
```
git switch pa11y
M	_data/datastore-metadata
M	_themes/jekyll-theme-legumeinfo
Switched to branch 'pa11y'
Your branch is up to date with 'origin/pa11y'.
```
Should we do `submodule update` essentially any time we see that a submodule has changed? The following is what I did Friday (#84):
```
  git submodule update --remote _themes/jekyll-theme-legumeinfo
  git commit -m 'update theme submodule'
  git commit -m 'update theme submodule' _themes/jekyll-theme-legumeinfo
  git submodule update --remote _data/datastore-metadata
  git commit -m 'update datastore-metadata submodule' _data/datastore-metadata
  git branch
  git push origin update-submodules
```

**Comment by nathanweeks** [comment]
A few options, depending on the goal. Assuming the current (PR) branch is the one specified in the PR:

1. `git submodule update` would checkout the versions of submodules specified in the current branch.

2. If the a submodule in the current branch are behind those in "main", `git merge main` followed by `git submodule update` should have a similar effect to what the result would be after the PR is merged (AFAIK the content should be the same no matter which direction the merge has occurred). Optionally, this can be `git push`'ed back to the PR branch to run through CI/CD to ensure those checks pass.

3. If you want to update any submodules to the latest versions from their upstream source for any reason, then `git submodule update --remote <submodule_path>` would do that. This of course is only reflected locally, and would need to be pushed to a remote branch for the purpose of CI/CD or to submit a PR.

**Comment by maxglycine** [comment]
I am not sure what it is that I am supposed to review.  Pa11y seems to tell you if you are 508 compliant, yet I did not see any chatter from the loading process (in code spaces) that seemed to relate to that program.  Are we then to conclude we are compliant?

**Comment by nathanweeks** [comment]
> I am not sure what it is that I am supposed to review. Pa11y seems to tell you if you are 508 compliant, yet I did not see any chatter from the loading process (in code spaces) that seemed to relate to that program. Are we then to conclude we are compliant?

The "Deploy Jekyll site to Pages / pa11y (push)" check in this PR (GitHub Actions workflow job) shows "Failing after 10m". I supposed the job could be renamed from "pa11y" to, e.g., "accessibility checks" to make its purpose more obvious? 

From codepsaces, one could do `make pa11y` to manually install/run the pa11y-ci checks (which take a few minutes---eventually this could be sped up once concurrent checks work, but that functionality seems to be broken in the current pa11y-ci)

**Review by maxglycine — COMMENTED** [review]
I am not sure what to look for.  I did find that  pa11y reported a non-zero exit code on the code space.  It seems to have had a lot of warnings.  So should we go through all of them making changes?  Some of them were like "color contrasts in CMap need to be improved" are not things we can change.  What is the proposed remediations here?

**Comment by nathanweeks** [comment]
> I am not sure what to look for. I did find that pa11y reported a non-zero exit code on the code space. It seems to have had a lot of warnings. So should we go through all of them making changes? Some of them were like "color contrasts in CMap need to be improved" are not things we can change. What is the proposed remediations here?

Somebody probably needs to go through the results and decide what's obviously noise (and should be ignored by configuration) and what should be addressed. The all-default configuration (except substituting the "axe" runner) in this PR just provides a starting point.

If there are no show-stopping concerns with this starting configuration, I'll merge so accessibility results can be tracked, and HTML/CSS changes & configuration tweaks can be made in the future as they're decided on.

**Pull request merged**
