### PR TITLE
GO enrichment blog post, and replace soybase.org -> legacy.soybase.org

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Essentially three changes:
1. New blog post about GO enrichment;
2. Link to the blog post from tools/analysis/go.html;
3. Throughout the site, replace https://soybase.org with https://legacy.soybase.org

Also, some tweaks to the "SoyBase Update" post to get the title and author/date lines to show up (see the blog instructions at https://github.com/legumeinfo/jekyll-theme-legumeinfo/).

### CODE REVIEW

**Comment by nathanweeks** [comment]
Might consider using gif for the images, which in this case consumes ~1/3 disk space of png, to slow repo size growth; e.g.:
```
sips --setProperty format gif GO_set1_biological.png GO_set1_biological.gif
```

**Comment by StevenCannon-USDA** [comment]
@nathanweeks Thanks for the suggestion. The sips app was new to me.
https://maeda.pm/2018/02/12/epic-command-line-moment-batch-convert-images-with-sips/

I did essentially the following (and removed some unused blog images at the same time):
```
mkdir gifs
sips -s format gif ./*png --out gifs/
rm *png
mv gifs/* .
```

**Comment by nathanweeks** [comment]
A couple suggested URL updates:
legacy.soybase.org/data/v2 -> data.soybase.org
legacy.soybase.org/data/annex -> data.soybase.org/annex

**Comment by StevenCannon-USDA** [comment]
@nathanweeks - Thanks for the URL corrections. I have made those changes.

**Comment by nathanweeks** [comment]
Minor suggestion: the [post_url](https://jekyllrb.com/docs/liquid/tags/#linking-to-posts) tag can link to a post without having to determine the generated permalink URL: `<a href="{% post_url 2024-07-01-go-enrichment %}">`

**Comment by StevenCannon-USDA** [comment]
@nathanweeks Thanks for the suggestion.
For some reason, it is not working though.
Results from a couple of attempts:
```
<a href="{% post_url 2024-07-01-go-enrichment %}"><b>this blog post</b></a> 

  Deprecation: A call to '{% post_url 2024-07-01-go-enrichment %}' did not match a post
  using the new matching method of checking name (path-date-slug) equality. Please make sure
  that you change this tag to match the post's name exactly.
       
<a href="{% post_url /blog/_posts/2024-07-01-go-enrichment %}"><b>this blog post</b></a>

  Deprecation: A call to '{% post_url /blog/_posts/2024-07-01-go-enrichment %}' did not
  match a post using the new matching method of checking name (path-date-slug) equality.
  Please make sure that you change this tag to match the post's name exactly.
```

**Review by maxglycine — COMMENTED** [review]
_@nathanweeks_ Great work.  Just a couple of things in the instructions (BOLDED)
GO enrichment analysis uses statistical tests to determine if a set of provided genes are statistically different than a comparison set (typically, the set of all genes in the organism), **_for each_** of the three main gene ontology aspects.

The [tools/analysis/go.html](https://cautious-space-potato-694rrxp7v7vhxpj-4000.app.github.dev/tools/analysis/go.html) page offers services for annotating **_your gene list_** with GO accessions and for calculating GO enrichment, using the method described in [Morales et al. (2013)](https://dx.doi.org/10.1071/FP12296).

At [GlycineMine](https://mines.legumeinfo.org/glycinemine/begin.do), enrichment can be calculated for genes from ANY Glycine accession and annotation in **_GlycineMine_** (there are more than 50 annotation sets as of mid-2024).

**_If you register with GlycineMine you will be able to save your gene list so that you can use the same list over and over again on the same tool or use that list on various GlycineMine tools._**  You can use the provided name if you wish (based on date and time), or you can give it a more meaningful name. Then click the green “Save a list of 10 Genes” button.

In the “Gene Ontology Enrichment” box, be sure to check each ontology aspect **_that you wish to search_**:

@StevenCannon-USDA @jd-campbell  @ChenProm-USDA

**Comment by StevenCannon-USDA** [comment]
Thanks for the corrections, @maxglycine. I have made those changes.
@nathanweeks : you were right about the link to the blog post. For our future reference, here is what worked:
```
{% post_url /blog/2024-07-01-go-enrichment %}
```
... whereas the absolute link to the file is
```
blog/_posts/2024-07-01-go-enrichment.md
```
... so Jekyll must be stripping `_posts/`.

I think this PR is ready for re-review and then approval, if someone would please.

**Review by maxglycine — APPROVED** [review]

**Pull request merged**
