### PR TITLE
Soy2025 Meeting registration info 

### PR DESCRIPTION
**Pull request by jd-campbell**
Hello: 
@ChenProm-USDA  Please review the ui-kit/html coding. You are welcome to make changes to the UI. 

@StevenCannon-USDA  Please review the wording/grammar for the three Soy2025 pages.  I also removed the sentence "We anticipate that that this transition will continue through 2024." from the front page.

### CODE REVIEW

**Review by StevenCannon-USDA — APPROVED** [review]
Looks good to me. I made some edits to the soy_biennial page.

**Review by ChenProm-USDA — APPROVED** [review]
Looks good.

**Comment by jd-campbell** [comment]
@nathanweeks 
The check-links job has failed. When I check the details from the failed check-link all the links are external and have a 406 error code. Is there anything I can do to fix this?

**Comment by nathanweeks** [comment]
HTTP 406 error eventually fixed, though now a mine link is causing HTTP 500. Will investigate.

Also, recommend changing `/data/annex/` URLs to `/annex/`.

**Comment by nathanweeks** [comment]
Seems like the mines don't like HTTP header `Accept: */*`, so ignoring the HTTP 406 for now. check-links passes.

**Comment by StevenCannon-USDA** [comment]
I removed accordion collapse (at least for now) from the community page, since I think the page is not really big enough to need it, and it was starting to annoy me to need to uncollapse the content every time I visited. 
Links are all passing not. Will merge to main.

**Pull request merged**
