### PR TITLE
Trait search

### PR DESCRIPTION
**Pull request by That-Thing**
Adds trait search web component into Jekyll.

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
The interface looks good to me (implemented as spec'd), but at least as I am testing it (served locally), I see "No data found" for reasonable queries (e.g. for any of the example searches). In contrast, the gene search page gives expected results.

**Comment by That-Thing** [comment]
Oh, that might be because I was testing it with GraphQL set to glycinemine, which has all of the traits.

**Comment by StevenCannon-USDA** [comment]
> Oh, that might be because I was testing it with GraphQL set to glycinemine, which has all of the traits.

But isn't glycinemine the correct target?

**Comment by That-Thing** [comment]
Glycinemine is the correct target, but the [GraphQL server](https://graphql.lis.ncgr.org/) is pointed to legumemine (I think).

**Comment by StevenCannon-USDA** [comment]
> Glycinemine is the correct target, but the [GraphQL server](https://graphql.lis.ncgr.org/) is pointed to legumemine (I think).

Sounds like a question for @alancleary or @sammyjava. Is there a way to point the GraphQL server to a particular mine?

**Comment by sammyjava** [comment]
Yeah, the mine URI is set in the .env file. We change it all the time to test things.
```

shokin@morangie:~/graphql-server$ cat .env
PORT=4444
INTERMINE_URI=https://mines.dev.lis.ncgr.org/minimine/service
MICROSERVICES_URI=https://services.lis.ncgr.org
```
(In this case I'm hitting dev MiniMine which is running 5.1.0.4 since that's what I'm working on.)

**Comment by alancleary** [comment]
> > Glycinemine is the correct target, but the [GraphQL server](https://graphql.lis.ncgr.org/) is pointed to legumemine (I think).
> 
> Sounds like a question for @alancleary or @sammyjava. Is there a way to point the GraphQL server to a particular mine?

Yes. This functionality is documented in the [graphql-server readme](https://github.com/legumeinfo/graphql-server#env-file).

**Comment by StevenCannon-USDA** [comment]
A remedial question: where should the .env file reside? For that matter, in a Jekyll instance, where IS the GraphQL server?

**Comment by That-Thing** [comment]
The .env file resides in the root of the GraphQlL directory.  
In Jekyll, the GraphQL server is set with the `graphql_uri` variable in _config.yml,

**Comment by StevenCannon-USDA** [comment]
Thanks, Simon. I hope eventually to come up to speed on this. If you can add that file, I'll review the PR again.

**Comment by That-Thing** [comment]
the .env file is just for the GraphQL server, which isn't part of the Jekyll site. Our problem is that there's no running GraphQL server running pointed to Glycinemine.

**Comment by sammyjava** [comment]
> the .env file is just for the GraphQL server, which isn't part of the Jekyll site. Our problem is that there's no running GraphQL server running pointed to Glycinemine.

Do you want us to fire one up alongside the one that's running on LegumeMine on our server? That's running on
```
graphqluri: https://graphql.lis.ncgr.org/
```
I don't know where the one running on ArachisMine is, tbh: @svengato? Ahhh nevermind, @svengato, I found it on jicama on the same VM as the site.

**Comment by sammyjava** [comment]
`graphql.soybase.ncgr.org` would make sense as a domain if it's at NCGR.

**Comment by svengato** [comment]
Production: https://www.peanutbase.org/graphql
Development: https://dev.peanutbase.org/graphql

**Comment by StevenCannon-USDA** [comment]
> Do you want us to fire one up alongside the one that's running on LegumeMine on our server? 

That would be good. Seems sensible that it's managed alongside the LegumeMine server.

**Comment by sammyjava** [comment]
OK, y'all good with `https://graphql.soybase.ncgr.org/`  as the public URI? (Since Soybase isn't LIS and I'd rather avoid the hassle of creating a soybase.org domain since no one sees it.)

**Comment by StevenCannon-USDA** [comment]
`https://graphql.soybase.ncgr.org/`
OK by me. Shouldn't be too difficult to change if we decide to host on another platform in the future. But I think for now, the hosting is a bit up-in-the-air as we explore cloud options.

**Comment by sammyjava** [comment]
Yeah and actually we want an NCGR domain that you'd CNAME to, anyway. I've got the domain, I'll set up the server....

**Comment by sammyjava** [comment]
OK, you got it.

http://graphql.soybase.ncgr.org/
https://graphql.soybase.ncgr.org/

The DNS is a bit wonky right now, but hopefully we'll get that cleared up soon. I've tested it when the domain resolves and it's got a GraphQL server on it. :)

The domain is just a CNAME to jicama.lis.ncgr.org by the way.

**Comment by That-Thing** [comment]
I can't reach the server in a browser my end but dig works, so I'm assuming that the DNS are just slow to update. I updated the config to include the new server, so when that starts working properly @StevenCannon-USDA can review the PR.

**Comment by sammyjava** [comment]
Should be good now, Zach here fixed the DNS2 problem that was causing issues. You had a 50/50 chance of resolving on first try, and if you missed it, your local caching would probably continue non-resolving it. Should be 100% now.

**Comment by StevenCannon-USDA** [comment]
Still getting "service unavailable" (after clearing cache) on https://graphql.soybase.ncgr.org/

**Comment by That-Thing** [comment]
That seems like a server issue, not a DNS one. At least we know that the domain is working correctly.

**Comment by sammyjava** [comment]
Yeah that was the server being down, it turns out because mines.legumeinfo.org couldn't be resolved it turns out because the DNS server was restarted while graphql-server was doing its polling of the mine properties. @alancleary that polling thing crashing the server is really a serious fault -- is there an issue to fix that? Seems I recall there is.

In any case, it's back up.

**Comment by alancleary** [comment]
> Yeah that was the server being down, it turns out because mines.legumeinfo.org couldn't be resolved it turns out because the DNS server was restarted while graphql-server was doing its polling of the mine properties. @alancleary that polling thing crashing the server is really a serious fault -- is there an issue to fix that? Seems I recall there is.
> 
> In any case, it's back up.

Yes, see https://github.com/legumeinfo/graphql-server/issues/103. And polling isn't the issue. If ANY mine request fails the server will come down. That's the default behavior of Apollo.

**Comment by StevenCannon-USDA** [comment]
I am seeing the server now, but am still getting "No data found" as the web component response.

**Comment by That-Thing** [comment]
I added another commit changing the GraphQL uri in the config earlier. Make sure you pull, as without that the web components will still send requests to the old uri. That being said, `https://graphql.soybase.ncgr.org/` is still giving a 503 error, so the search won't work either way.

**Comment by sammyjava** [comment]
> > Yeah that was the server being down, it turns out because mines.legumeinfo.org couldn't be resolved it turns out because the DNS server was restarted while graphql-server was doing its polling of the mine properties. @alancleary that polling thing crashing the server is really a serious fault -- is there an issue to fix that? Seems I recall there is.
> > In any case, it's back up.
> 
> Yes, see [legumeinfo/graphql-server#103](https://github.com/legumeinfo/graphql-server/issues/103). And polling isn't the issue. If ANY mine request fails the server will come down. That's the default behavior of Apollo.

For sure, but no one was using the server and it crashed because it was polling. But certainly we don't want to crash, period.

**Comment by sammyjava** [comment]
Oh, hell, my apologies: I had a typo in the mines URL ("leguminfo"). So that's why it crashed, although we do need to fix that. It's up now with the appropriate mine URL.

**Comment by That-Thing** [comment]
Trait search works on my end with the new server.

**Comment by StevenCannon-USDA** [comment]
Works nicely for me now! Thanks for the hard work, @alancleary @sammyjava @That-Thing.
Before approving, I have one (I think) minor change to request, and a question about linkouts.
* Can the example text under Author be changed? "Blair" gives no result for soybean. I would suggest "Specht" as a replacement.
 * Regarding linkouts - at least the Study Name should be a linkable - and maybe the DOI in the . Is there a plan to link to a  modal link box, similar to the gene search component?

**Comment by alancleary** [comment]
> Can the example text under Author be changed? "Blair" gives no result for soybean. I would suggest "Specht" as a replacement.

Currently, no. But there is an issue in the web-components repo to make the example text customizable: https://github.com/legumeinfo/web-components/issues/277. This should be real easy to implement but I have higher priorities to attend to before I start my vacation on Friday. I'll gladly review a PR if someone else wants to take care of it before COB tomorrow(!).

> Regarding linkouts - at least the Study Name should be a linkable - and maybe the DOI in the . Is there a plan to link to a  modal link box, similar to the gene search component?

If I'm understanding you correctly, these are site-specific features that will need to be implemented in soybase. If we decided this is something we want every site to have, then the implementation can be added to the GraphQL scripts in the Jekyll theme.

**Comment by That-Thing** [comment]
I can work on getting customizable example text if there's no one else doing it.

**Comment by alancleary** [comment]
> I can work on getting customizable example text if there's no one else doing it.

Sounds good. Do you mind implementing it on all components?

**Comment by StevenCannon-USDA** [comment]
> If I'm understanding you correctly, these are site-specific features that will need to be implemented in soybase. If we decided this is something we want every site to have, then the implementation can be added to the GraphQL scripts in the Jekyll theme.

I think it would make sense to implement the same type of link-outs from this component for all the sites. Specifically, the Study Name (column 1) is associated with a nice mine report page, e.g. https://mines.legumeinfo.org/glycinemine/gwas:mixed.gwas.Fang_Ma_2017

I'll start a new issue for this (for the new year).

**Comment by sammyjava** [comment]
Yeah, there's nothing soybean-specific about linking to the mine report pages for GWAS and QTLStudy. Any mine that has traits will have GWAS and/or QTLStudy to link to. And four mines have them: ArachisMine, GlycineMine, PhaseolusMine, VignaMine.

**Comment by StevenCannon-USDA** [comment]
I was about to re-review and approve this PR, since the functionality all looked good (apart from the minor issue of changing the search example text, and linkouts - which will become a separate issue) -- but I see that there are nontrivial new conflicts with "main" now, after the theme updates:
```
assets/js/graphql/get-organisms.js
assets/js/graphql/index.js
```
Can you have a look at those (when available), @That-Thing and/or @nathanweeks? I suspect we will just want to use the new code, but I am not sure. 
[Edit: removed comment about an error, which apparently was due to a caching]

**Comment by That-Thing** [comment]
I added example [text changing functionality](https://github.com/legumeinfo/web-components/pull/304) into the web components, so we're just waiting on a release to be made so it's pushed to the CDN.

I'll also have a look and resolve the conflicts.

**Comment by That-Thing** [comment]
Changes are merged, so the PR should be ready for re-review.

**Comment by StevenCannon-USDA** [comment]
At least at the moment, both the trait search and gene search pages (`tools/search/trait.html`, `tools/search/gene.html`) are coming up blank. This is after `make clean` / `make`

**Comment by That-Thing** [comment]
They seem to be coming up for me. Refreshing your browser cache might fix the issue.

**Comment by StevenCannon-USDA** [comment]
Weird. Still no - including in a fresh browser.
In the source, I see the javascript (`import {getTraitOrganismsFormDataFunction ...`), but nothing shows in the page.
Console message:
`Uncaught TypeError: Failed to resolve module specifier "lis-graphql". Relative references must start with either "/", "./", or "../".`

**Comment by That-Thing** [comment]
Could you check if it loads the graphql js files in your browser debugger?
image

**Comment by StevenCannon-USDA** [comment]
@That-Thing I am not finding that debugger view in my local browser developer tools (Chrome, Safari), but the javascript is present in my local _sites directory: 
```
find . -name get-traits.js
./_site/assets/js/graphql/get-traits.js
./assets/js/graphql/get-traits.js
```
However, I see the same behavior (empty page) in codespaces. There (and locally), this is the console error message:
`TypeError: Module name, 'lis-graphql' does not resolve to a valid URL.`

**Comment by That-Thing** [comment]
Can you make sure that `assets/js/graphql/index.js` is present? It seems that the importmap in the head isn't finding it.
```html
  <!-- opt-in code for integrating GraphQL with LIS Web Components -->
  <script type="importmap">
    {
      "imports": {
        "lis-graphql": "{{ "assets/js/graphql/index.js" | relative_url }}"
      }
    }
  </script>
  ```

**Comment by StevenCannon-USDA** [comment]
It seems to be:
```
cat assets/js/graphql/index.js  
export * from './get-genes.js';
export * from './get-traits.js';
export * from './get-linkouts.js';
export * from './get-organisms.js';
export * from './modal.js';
export * from './query.js';%                                                                                      

find . -name index.js
./_themes/jekyll-theme-legumeinfo/uikit/tests/js/index.js
./_themes/jekyll-theme-legumeinfo/uikit/src/js/core/index.js
./_themes/jekyll-theme-legumeinfo/uikit/src/js/util/index.js
./_themes/jekyll-theme-legumeinfo/uikit/src/js/components/index.js
./_themes/jekyll-theme-legumeinfo/uikit/src/js/api/index.js
./_site/assets/js/graphql/index.js
./assets/js/graphql/index.js
```

**Comment by That-Thing** [comment]
That's very strange. It seems from the error that the import url is somehow being rendered as `assets/js/graphql/index.js` instead of `/assets/js/graphql/index.js` on your computer. 
I can't seem to recreate the issue, which makes this all the more confusing.

**Comment by nathanweeks** [comment]
> It seems to be:
> 
> ```
> cat assets/js/graphql/index.js  
> export * from './get-genes.js';
> export * from './get-traits.js';
> export * from './get-linkouts.js';
> export * from './get-organisms.js';
> export * from './modal.js';
> export * from './query.js';%                                                                                      
> 
> find . -name index.js
> ./_themes/jekyll-theme-legumeinfo/uikit/tests/js/index.js
> ./_themes/jekyll-theme-legumeinfo/uikit/src/js/core/index.js
> ./_themes/jekyll-theme-legumeinfo/uikit/src/js/util/index.js
> ./_themes/jekyll-theme-legumeinfo/uikit/src/js/components/index.js
> ./_themes/jekyll-theme-legumeinfo/uikit/src/js/api/index.js
> ./_site/assets/js/graphql/index.js
> ./assets/js/graphql/index.js
> ```

I'm also seeing:

```
./_themes/jekyll-theme-legumeinfo/assets/js/graphql/index.js
```

Also, note that the JS files in assets/js/graphql were removed in the main branch, as they already exist in jekyll-theme-legumeinfo. I think this PR is proposing to update assets/js/graphql to web-components v1.2.0? Perhaps to maintain consistency with the theme (and allow other sites using the theme to benefit), a PR could be made to jekyll-theme-legumeinfo to update its bundled web components to v1.2.0, and then subsequently the jekyll-theme-legumeinfo submodule in this repo can be updated?

**Comment by That-Thing** [comment]
Oh right, I added the unnecessary ones back in without noticing that. 
The modified ones will have to stay since they are needed for the trait search to work.

**Comment by StevenCannon-USDA** [comment]
> a PR could be made to jekyll-theme-legumeinfo to update its bundled web components to v1.2.0, and then subsequently the jekyll-theme-legumeinfo submodule in this repo can be updated?

Sounds like that's the thing to do. Probably best for @That-Thing to do that - if you would, please - though after New Years is fine. I am just doing some off-schedule catch-up now.

**Comment by That-Thing** [comment]
Will do

**Comment by That-Thing** [comment]
@StevenCannon-USDA https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/72 was merged into main, so hopefully your issue should be fixed. Can you please update the submodule and check if it works?

**Comment by StevenCannon-USDA** [comment]
Finally, yes! Thanks for your persistence on this, @That-Thing.
I do need to report two remaining issues though -- one that looks like an edge-case bug and one that may be either an omission or an enhancement, depending on the implementation details.
 - The search fails when Study Type is set as "QTL". It succeeds with "--any--" and "GWAS". To reproduce: set Traits as "seed weight" and Study Type as "QTL".
 - The example text under Traits, Publication ID, and Author is missing. Was this intended?

**Comment by That-Thing** [comment]
Oh thanks for catching that bug. I created [another PR](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/73) in the theme repository.
This was happening because the study type variable was a const which prevented it from being modified as it was supposed to if the study type was QTL.

After this PR is merged this will be fixed.

**Comment by StevenCannon-USDA** [comment]
This fixes the bug related to Study Type, but I see a new one. This one is tricky.

I noticed that the example under Publication ID (10.1371/journal.pone.0054985) fails - which is unexpected since the publication is present in GlycineMine. I think the problem is that get-traits.js is looking for the PublicationID in the text of Description; but the Description may or may not contain a DOI or PMID. The QTL records usually happen to contain a DOI; but this isn't guaranteed.

So, much better (if possible) would be to look for the PublicationID in the pubMedId and doi field. The DOI should be in doi and PMID should be in pubMedId.

**Comment by That-Thing** [comment]
This would be an issue with the GraphQL query for trait search and not the JS that handles all given data. `publicationId` is a parameter for the `traits` query, so get-traits.js just passes the given publication ID to the query. 
I'm guessing this is something to ask @sammyjava about.

**Comment by StevenCannon-USDA** [comment]
I think I'll go ahead and approve and close this PR and will open a new issue regarding the GraphQL query.
@sammyjava - what is the best location for such an issue? See the gist of the question above, about PublicationID.
[Edit] ... but I think someone else needs to do the review and approval - probably since I made a minor contribution to the code (fixing a merge conflict with navigation).
[Edit 2] ... Never mind. I was able to review after all.

**Review by StevenCannon-USDA — APPROVED** [review]
Will approve and merge. Will open a new issue regarding PublicationID query.

**Pull request merged**
