### PR TITLE
Gene translator page (correspondences via pangenes)

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Landing page (tools/translate/) for doing gene-name lookups / translation / correspondence searches.

One item that's not finished is the link to the pangene search page. That would be added when that Web Component page is ready.

We may also add a component that queries Glycine mine for a provided list, but I think we should get the simpler static page in place first.

### CODE REVIEW

**Review by maxglycine — CHANGES_REQUESTED** [review]
The “Pangene search tool” link is circular, it links to the current page.
The user will need an itemization of the contents of the total “pangene” collection similar to the reference list or a link to some other page that lists them all.
I could not find any tool name that contained the word “pangene”.  Has one been built?
Previously, SB has relied on the JGI file to determine “correspondence”. There will have to be some text somewhere that describes how we are determining “correspondence”, in other words pandagma’s workings will have to be explained somewhere, a GitHub page perhaps? Just a link to it will do.

**Comment by StevenCannon-USDA** [comment]
> The “Pangene search tool” link is circular, it links to the current page.

Right; "One item that's not finished is the link to the pangene search page. That would be added when that Web Component page is ready."

> will have to be some text somewhere that describes how we are determining “correspondence”

Good point. Will do.

**Comment by StevenCannon-USDA** [comment]
@maxglycine 
>The “Pangene search tool” link is circular, it links to the current page.

I've removed this link for the time-being. Will re-add when the search tool is in place.

> The user will need an itemization of the contents of the total “pangene” collection similar to the reference list or a link to some other page that lists them all.

Good point. I have added lists of the annotations that are available in each table.

>... pandagma’s workings will have to be explained somewhere, a GitHub page perhaps? Just a link to it will do.

I have added a Methods section, with link to the repository (and a more detailed description). A short manuscript is in progress.

**Review by maxglycine — DISMISSED** [review]
Thanks for the work.  We will need to make this page dynamic with the ability to submit a list of genes either in a text box or file upload in the future.  Right now, the .gz files can not be extracted using the usual desktop tools for extraction necessitating going to the command line and issuing the gunzip command.  This is not optimal.  They should be just zipped (.zip).  That way the windows and mac users can easily extract it using the gui tools.  Once that has been done it will be good to go.

**Comment by StevenCannon-USDA** [comment]
@maxglycine - Providing these files in zip format would make them the only zip-formatted files in the Data Store. Gzipped files are the norm for download files. For example, download files from Phytozome and GenBank are in .gz format. It's the common compression format in this discipline. Mac and PC users can extract a .gz file using gui tools. In any case, people who do computational biology should be able to work with the common formats.

**Review by maxglycine — APPROVED** [review]
OK pending future improvements

**Pull request merged**
