### PR TITLE
Update tools/snp50k/index.html with links to SNP50k markers on WM82.A6

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Added links to JBrowse WM82.A6

Problem -- flagging @nathanweeks or @ChenProm-USDA : I can't see how to update jekyll-theme-legumeinfo.
I have tried:
```
  git submodule update --remote _themes/jekyll-theme-legumeinfo
  git commit -m 'update theme submodule' _themes/jekyll-theme-legumeinfo
```

### CODE REVIEW

**Comment by nathanweeks** [comment]
In the "main" branch, it looks as though the _themes/jekyll-theme-legumeinfo git submodule already points to the latest commit in the legumeinfo/jekyll-theme-legumeinfo repo.

**Comment by StevenCannon-USDA** [comment]
> In the "main" branch, it looks as though the _themes/jekyll-theme-legumeinfo git submodule already points to the latest commit in the legumeinfo/jekyll-theme-legumeinfo repo.

It may be that the problem is just on my end, and that the PR is fine as-is. 

My understanding of submodules is lacking. Here is what I see with `git diff _themes/jekyll-theme-legumeinfo`:
```
diff --git a/_themes/jekyll-theme-legumeinfo b/_themes/jekyll-theme-legumeinfo
--- a/_themes/jekyll-theme-legumeinfo
+++ b/_themes/jekyll-theme-legumeinfo
@@ -1 +1 @@
-Subproject commit 51fdcb9f017b61f775c9f3e56b03e7bf4460cf96
+Subproject commit 51fdcb9f017b61f775c9f3e56b03e7bf4460cf96-dirty
```

How do I sync _themes/jekyll-theme-legumeinfo to the remote submodule's "main"? If I cd to _themes/jekyll-theme-legumeinfo, I get "HEAD detached".
The changes in the submodule, btw, are `modified:   assets/uikit (new commits)`

**Comment by nathanweeks** [comment]
Are there any uncommitted changes in _themes/jekyll-theme-legumeinfo? What does `git status` show?

`git submodule update --recursive` from the superproject should recursively update the working tree of the submodules to reflect the commits that are pointed to by the superproject.

**Comment by StevenCannon-USDA** [comment]
@nathanweeks - I *think* I am back in business now. Earlier today I did this:
```
  git checkout --recurse
    cd _themes/jekyll-theme-legumeinfo/
    git checkout --recurse v1.3.0
    cd ../..
```
and now `git status` shows `nothing to commit, working tree clean`.

So, I think this is ready for review & merge, if the changes look OK.

**Review by nathanweeks — APPROVED** [review]
LGTM, though I'll proffer a Liquid loop to generate all rows for the table (feel free to use or not):
```
    {% assign assemblies = "1,2,4,6" | split: "," %}
    {% for assembly in assemblies %}
    <tr>
      <th><b>Wm82.a{{ assembly }}</b></th>
      {% for chromosome in (1..20) %}
      {% assign chr = chromosome | prepend: '00' | slice: -2,2 %}
      <td><a href="/assets/js/jbrowse/?assembly=Wm82.gnm{{ assembly }}&tracks=Wm82.gnm{{ assembly }}.ann1,Wm82.gnm{{ assembly }}.mrk.SoySNP50K&loc=glyma.Wm82.gnm{{ assembly }}.Gm{{ chr }}:1-1000000" target="_blank">Gm{{ chr }}</a></td>
      {% endfor %}
    </tr> 
    {% endfor %}
```

**Comment by StevenCannon-USDA** [comment]
> ... a Liquid loop to generate all rows for the table (feel free to use or not):

Thanks. I'll add that. I was also thinking that such a thing would be preferable.

**Pull request merged**
