### PR TITLE
Soynam updates2

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Opening a variant of the SoyNAM-updates branch from earlier today. That branch didn't merge to main because it had trailing spaces in a yaml file.

Other changes in this branch: added parent-request links to SoyNAM/index.html, and added Return links to the SoyNAM request pages.

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
@nathanweeks - There is a weird internal link failure
https://github.com/soybase/jekyll-soybase/actions/runs/10891169323/job/30221641394?pr=167
... complaining:
```
* At ./projects/soynam_2014/index.html:573:

  internally linking to /projects/soyNAM/SoyNAM_Parent_request.html, which does not exist
```
As far as I can tell, that file is present and accessible.

**Comment by nathanweeks** [comment]
`/projects/soyNAM/...` is probably accessible on a case-insensitive filesystem, but on a case-sensitive filesystem the URL-path would need to be `/projects/SoyNAM/...`'

Also some merge conflicts; would probably want to merge main & address those or create a new branch from main.

**Comment by StevenCannon-USDA** [comment]
> `/projects/soyNAM/...` is probably accessible on a case-insensitive filesystem, but on a case-sensitive filesystem the URL-path would need to be `/projects/SoyNAM/...`'

Sure enough. That link with the wrong case was in `_data/projects/SoyNAM_2014/project_details.yml` -- a place I should have looked but didn't (incidentally, Jekyll-datapage-generator lowercases the path, producing `projects/soynam_2014/index.html` -- which is the page source that gets link-checked).

**Review by maxglycine — APPROVED** [review]
Looks OK to me

**Review by maxglycine — COMMENTED** [review]
Looks OK to me

**Pull request merged**
