### PR TITLE
Add new page of gene expression resources, and add link to trait terms from trait association search page

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
- Added a page of expression resources, similar to CoNekT landing page pub specific for soybean.
- Added link to trait terms and categories at trait association search page.
- Removed trait-terms page as a separate link from Tools menu & page, since its main use is to facilitate trait searches.

### CODE REVIEW

**Review by maxglycine — COMMENTED** [review]
The page is ok.  But if we are going to bring up the eFP figure here, we will need to different links to the four eFP pictures. In the instructions, you specify that Wm82.a2 gene names are to be used in the tool, so I don't think we need to go through the gene search tool.  If anything, we should have a link to the Gene-name Translator tool from this page to make it easier to "convert" names.  The situation is a little messy since not all Wm82.a2 genes are expressed in either the atlases and or the embryonic and seed tissues.  When this happens a JSON payload of  '{"wasSuccessful": false, "error": "Failed to retrieve image. Data for the given gene may not exist."}' is returned. If it is successful, a URL to the picture is returned.

https://bar.utoronto.ca/api/efp_image/efp_soybean/soybean/Absolute/Glyma.15g026400

https://bar.utoronto.ca/api/efp_image/efp_soybean/soybean_severin/Absolute/Glyma.15g026400

http://bar.utoronto.ca/api/efp_image/efp_soybean/soybean_embryonic_development/Absolute/Glyma.15g026400

http://bar.utoronto.ca/api/efp_image/efp_soybean/soybean_heart_cotyledon_globular/Absolute/Glyma.15g026400

These are the links to the Libault (Atlas) Severin (Atlas), Danzer (Embryonic Development) and Pelieter (Seed Compartments) datasets .

If you still want to go to the BAR eFP site, we will have to ask BAR how to get to the other views.  I tried modifying the BAR URL and I could not get it to work.

_______________ UPDATE_____________________
I was able to find a URLs for the soybean pictures at BAR.

The URLs are:
https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean&mode=Absolute&primaryGene=Glyma06g47400&secondaryGene=Glyma06g47390&useThreshold=&threshold=15.0&grey_low=None&grey_stddev=None

https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean_severin&mode=Absolute&primaryGene=Glyma06g47400&secondaryGene=Glyma06g47390&useThreshold=&threshold=35.08&grey_low=None&grey_stddev=None

https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean_embryonic_development&mode=Absolute&primaryGene=Glyma06g47400&secondaryGene=Glyma06g47390&grey_low=None&grey_stddev=None

https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean_heart_cotyledon_globular&mode=Absolute&primaryGene=Glyma06g47400&secondaryGene=Glyma06g47390&useThreshold=&threshold=35.67&grey_low=None&grey_stddev=None

And there is leaf senescence from Anne's Dissertation
https://bar.utoronto.ca/efpsoybean/cgi-bin/efpWeb.cgi?dataSource=soybean_senescence

You can actually get to all the others from one URL by changing the "Data Source" pull down.  You can use a Wm82.a1 gene name or a Wm82.a2 gene name to query with.  They did the conversions where possible. Everything after the &primaryGene is optional and can be changed in the tool.  The mode is important.  It should be set to "Absolute" to get the correct color scale.

@StevenCannon-USDA @jd-campbell @ChenProm-USDA

**Comment by StevenCannon-USDA** [comment]
Thanks for finding the BAR resources, @maxglycine. I have added those as direct search fields on the page.
I didn't add a link to Annie's expression data (`soybean_senescence`), since that seems to be broken (should be reported to the BAR group). It looks like a splice variant number (`.1`) is getting added to the query gene ID.

I also added a quick-link on the home page to the expression-resources page.

**Review by maxglycine — COMMENTED** [review]
I note that you have added more boxes on the front page.  I don't think we want to add more.  
The expression landing page looks good.  I note that the option "" lead to the gene search page which was pre-filled with the gene name (Great!, I did not think that was possible).  However, for the naive person, what to do to get to the promised "plot" (histogram) was not clear.  Could the link go directly to the GlycineMine page for the gene? @StevenCannon-USDA @jd-campbell

**Comment by StevenCannon-USDA** [comment]
> I note that you have added more boxes on the front page. I don't think we want to add more.

Yes. I thought that a link to the expression resources might be worth a button. The other two buttons to fill out that row seemed worthwhile to me too. Researchers may want to check other legumes for context, and we have no other direct link to legumeinfo.org in the site - but I don't feel strongly about it. @jd-campbell and @maxglycine -- remove this line of buttons, or keep them?

> Could the link go directly to the GlycineMine page for the gene?

Yes, though the Gene Search component does have some utility that a direct link lacks (the Gene Search doesn't require prefixing, and gives links to the gene family and pangene set, etc). Why don't we provide both types of links. I'll need your help to fix the search form, @ChenProm-USDA . See the first form under 
<b>Expression plot in GlycineMine</b>
That form should construct links with the following structure:
```
https://mines.legumeinfo.org/glycinemine/gene:glyma.Wm82.gnm2.ann1.Glyma.15G026400
https://mines.legumeinfo.org/glycinemine/gene:glyma.Wm82.gnm2.ann1.Glyma.12G040000
```

**Comment by ChenProm-USDA** [comment]
@StevenCannon-USDA I implemented the functionality that you asked for please check.  Also refactor some of the code and made styling updates.

**Comment by StevenCannon-USDA** [comment]
Nice changes, @ChenProm-USDA. I like the styling and the code cleanup.
I don't think I am able to approve since I did the original commit; just commenting approvingly :-)

**Review by jd-campbell — CHANGES_REQUESTED** [review]
@StevenCannon-USDA` I was not done adding some info about the other two tools from CoNekT to the index page.  For some reason I can sync my changes to the branch.  So instead I have pasted my requested addition below this note. 



```<p>
  <b style="font-size:larger">Comparing Expression profiles of multiple genes</b><br>
  From the <b><a target="_blank" href="https://conekt.legumeinfo.org/profile_comparison/">CoNekT Compare Profiles page</a></b>, you can compare the expression of up to 50 genes on the same graph in each experimental condition or tissue
<br>To use this tool: 
<ul>
  <li>Change the species to 'Glycine max'</li>
  <li>Enter a list of gene identifiers, use the full ID name <i>glyma.Wm82.gnm2.ann1.</i>15g026400</li>
  <li>Click Show profiles</li>
</ul>
</p>

<p>
  <b style="font-size:larger">Create a custom heatmap with multiple genes</b><br>
  From the <b><a target="_blank" href="https://conekt.legumeinfo.org/heatmap/">CoNekT Create Custom Heatmap page</a>. <br>
  You can generate a detailed heatmap for a single species <i>(Default-tab)</i> and a cross-species comparative heatmap <i>(Comparative-tab).</i><br>
  Enter a list of gene identifiers, use the full ID name <i>glyma.Wm82.gnm2.ann1.</i>15g026400
</p>```

**Comment by ChenProm-USDA** [comment]
@StevenCannon-USDA 
@jd-campbell 

I added the changes and pushed it up.

**Review by jd-campbell — APPROVED** [review]
Thank you @ChenProm-USDA for your help.

**Comment by ChenProm-USDA** [comment]
@jd-campbell 
I restored this branch because there's a missing closing `</b>` ,in the heatmap portion of the code, that breaks the styling on everything after it.  I need to fix it.

**Comment by StevenCannon-USDA** [comment]
@ChenProm-USDA and @jd-campbell - while you're making changes, let's handle this as a PR again. There are some some minor styling and text changes that I think we should make at the same time.

**Comment by ChenProm-USDA** [comment]
@StevenCannon-USDA sounds good.  Let me know what needs to be changed.

**Comment by StevenCannon-USDA** [comment]
> @StevenCannon-USDA sounds good. Let me know what needs to be changed.

I'm done. Just some minor changes to the text.

**Pull request merged**
