### PR TITLE
GO term enrichment tool

### PR DESCRIPTION
**Pull request by nathanweeks**
Simple web form that uses GO term enrichment API.

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
I have tested the functions on the page. The page looks good to me and the pasted-gene-list works (though I see an error for some types of submitted data**).

For the "Upload a text file" option, I get this error:
`{"error":"500 - Internal server error","message":"Error in strsplit(glyma.list[[1]], \"\\r?\\n\"): non-character argument\n"}`

For the pasted-gene-list option, I get error `{"error":"500 - Internal server error","message":"Error in results[[i]]: subscript out of bounds\n"}` for this list:
```
Glyma.20G226200
Glyma.10G163600
Glyma.03G248300
Glyma.19G251400
Glyma.03G254000
Glyma.19G246300
```

but not for the following list - which is a superset of the list above:
```
Glyma.20G226200
Glyma.10G163600
Glyma.03G248300
Glyma.19G251400
Glyma.03G254000
Glyma.19G246300
Glyma.14G133900
Glyma.05G097000
Glyma.10G121200
Glyma.16G139200
Glyma.18G146800
Glyma.05G074700
Glyma.10G087600
Glyma.02G173100
Glyma.19G051300
Glyma.03G095100
Glyma.19G107900
Glyma.01G128900
Glyma.20G090600
Glyma.01G065200
Glyma.18G077200
```
I suspect that the submitted list has to have sufficient diversity in GO function. Genes from a single gene family are likely to fail. If this is the case (i.e. there are some statistical requirements for the statistical test), then perhaps add a note to that effect -- something like "This statistical test may fail on small gene lists with highly similar gene functions" (caveat that this is just my guess, and I haven't looked closely at the test).

**Comment by nathanweeks** [comment]
It looks like the gene models in the first list do not exist in assembly v4, whereas the second list contains a few that do. The API should be updated to provide a helpful diagnostic message for each gene model that isn't found.

**Comment by maxglycine** [comment]
I have looked at the tool.  It generally looks good.  Besides the ungraceful way it handles "missing" Wm82.a4 gene names, I copy-n-pasted a new a list of Wm82.a4 gene names and it errored out.  I am not sure I understand the "missing" names.  If I remember Michelles file, Wm82.a4 names that did not have a hit to Arabidopsis (how she got the GO annotations) had "no hit" in the AT column.  Maybe the script needs to be modified to  see if the annotation contains "no hit"?

I also note that there are no column headings on the "GO Annotation" results

**Comment by nathanweeks** [comment]
@maxglycine Could you provide a list that reproduces the error you observed?

**Comment by nathanweeks** [comment]
Still relevant. @maxglycine could you re-test to verify @weihuang12 's updates?

**Comment by StevenCannon-USDA** [comment]
Re-testing: I am still seeing problems that I don't understand.
Many gene lists give this error for the enrichment analysis:
`{"error":"500 - Internal server error","message":"Error in fisher.test(matrix(c(X[1], X[2], X[3], X[4]), nrow = 2)): all entries of 'x' must be nonnegative and finite\n"}`

In the tests below, all IDs are from glyma.Wm82.gnm4.ann1

```
OK:
Glyma.09G044100
Glyma.09G048500
Glyma.09G048600
Glyma.09G051100

OK:
Glyma.09G044100
Glyma.09G048500
Glyma.09G048600
Glyma.09G051100
Glyma.06G278400
Glyma.06G279400
Glyma.06G280700

OK:
Glyma.09G044100
Glyma.09G048500
Glyma.09G048600
Glyma.09G051100
Glyma.06G278400
Glyma.06G279400
Glyma.06G280700

x NOT OK (weird annotation result: GO terms and Arabidopsis genes, no soy IDs)
Glyma.03G038100
Glyma.03G038200
Glyma.03G038300

OK (a superset of the previous set)
Glyma.03G038100
Glyma.03G038200
Glyma.03G038300
Glyma.13G048100
Glyma.13G048500
Glyma.02G262700
Glyma.02G262900

x NOT OK (fails enrichment analysis)
Glyma.06G278400
Glyma.06G279400
Glyma.06G280700

x NOT OK (fails enrichment analysis)
Glyma.06G278400
Glyma.06G279400
Glyma.06G280700
Glyma.06G281200
Glyma.06G282800
Glyma.06G282000
Glyma.18G114100
Glyma.18G114200
Glyma.18G114300
Glyma.06G280400

x NOT OK (fails enrichment analysis)
Glyma.18G114100
Glyma.18G114200
Glyma.18G114300
```

**Comment by weihuang12** [comment]
@StevenCannon-USDA, I didn't see any error messages when I ran it on the codespace under r-version branch. 
docker compose run --rm go-enrichment test/testlist.txt Gmax4_GODB.tsv.gz ATH_GO_GOSLIM.030120.sorted.tsv.gz > go-enrichment.txt

Did you use different input file?

**Comment by StevenCannon-USDA** [comment]
@weihuang12 - I was on the `go-enrichment` branch. Is there a different one that I should test? I don't see `r-version`

**Comment by nathanweeks** [comment]
Confirming the issues that @StevenCannon-USDA saw with those inputs. Will troubleshoot.

**Comment by nathanweeks** [comment]
The annotation results have been fixed -- turns out that the R `apply()` function can return a list, but attempts to simplify the results by default (to a 2D array in this case) if dimensions permit, resulting in the (printed) output format changes. The fix was to add `simplify = FALSE` so `apply()` always returns a list.

The enrichment analysis still needs to be fixed. I'll look into that next.

**Comment by nathanweeks** [comment]
GO term enrichment analysis now works for the previously-failing cases. The issues were (1) not gracefully handling the case where all associated GO terms had either no molecular function and/or no biological function, and (2) not handling the case where there was exactly one unique GO term with molecular function or biological function (due to another base R idiosyncrasy, this time regarding [row name handling for one-row data frames](https://stackoverflow.com/a/55390036)).

**Review by StevenCannon-USDA — APPROVED** [review]
That was some tricky debugging, @nathanweeks.
All of my previous tests pass, as well as this set, constructed to be enriched for ion transport:
```
Glyma.03G128700
Glyma.19G131100
Glyma.04G092700
Glyma.06G094500
Glyma.08G164666
Glyma.08G164732
Glyma.08G164800
Glyma.09G099500
Glyma.09G122600
Glyma.15G262300
Glyma.15G262400
```
I'll approve and merge.

**Pull request merged**
