### PR TITLE
Ontology

### LINKED ISSUE #19: Static Page: /tools/ontology/

### PR DESCRIPTION
**Pull request by Cheehau0659**
Please help me add the description for ontology.

### CODE REVIEW

**Comment by maxglycine** [comment]
Cheehau:
The page looks exactly the same as it always did. That’s good. But when I clicked on the browse button, nothing happened. I was assuming that I would see an Amigo iFrame or something. Does it work for you?

**Comment by maxglycine** [comment]
Description 
SoyBase Soybean growth, development and structural ontology.

**Comment by Cheehau0659** [comment]
> Cheehau: The page looks exactly the same as it always did. That’s good. But when I clicked on the browse button, nothing happened. I was assuming that I would see an Amigo iFrame or something. Does it work for you?

Yes, every button works for me. I think you need to open the page in a new browser instead of using the browser in CodeSpace. I have problem opening the link in CodeSpace.

**Comment by maxglycine** [comment]
Interesting!

Rex Nelson

***@***.***

On Sep 26, 2023, at 6:57 PM, Chee Hau Fong ***@***.***> wrote:

﻿

Cheehau: The page looks exactly the same as it always did. That’s good. But when I clicked on the browse button, nothing happened. I was assuming that I would see an Amigo iFrame or something. Does it work for you?

Yes, every button works for me. I think you need to open the page in a new browser instead of using the browser in CodeSpace. I have problem opening the link in CodeSpace.

**Comment by StevenCannon-USDA** [comment]
The consensus for this page was for the following changes to be made before merging:
- Remove "./images/external.png" from the external links (and modify "style=" as needed)
- Put amigo.soybase.org into an iframe. 

For examples of iframed content, see maps/cmap-all/cmap-js.html and maps/cmap-all/index.html, which accesses  _layouts/iframe.html.

**Review by StevenCannon-USDA — CHANGES_REQUESTED** [review]
The consensus for this page was for the following changes to be made before merging:

- Remove "./images/external.png" from the external links (and modify "style=" as needed)
- Add a linked static page with contents corresponding with https://www.soybase.org/OntologyConversion.php
- Put amigo.soybase.org into an iframe.

For examples of iframed content, see maps/cmap-all/cmap-js.html and maps/cmap-all/index.html, which accesses _layouts/iframe.html.

**Comment by StevenCannon-USDA** [comment]
@Cheehau0659 - The conversion table that you added looks good; thanks for making that change. The main ontology page also looks good I think -- but after considering it a long time, I think that a simpler approach will be more appropriate for that content, and more consistent with the overall development approach for the Jekyll-SoyBase site. You did a good job of recreating the layout of the ontology.php page at SoyBase; but that required a large amount of custom javascript and css to be pulled into the page. We want to avoid that unless it is really necessary to accomplish some function. The additional custom html methods defeat the simplifications that Jekyll provides, and make the page more difficult to edit and maintain. Essentially: the software engineering perspective is to choose simpler solutions over more complex ones.

I have taken the same content for that page and made a variation, using simpler html methods and native Jekyll features. I also put the four ontology views into iframes - as it looks like you had begun doing with the tools/amigo directory.

So, the changes that I request are to use the ontology/index.html from the ontology2 branch to replace that content in your ontology/index.html, and add the four ontology/ subdirectories to complete the iframe pages.

**Comment by maxglycine** [comment]
The new version looks OK to me. the <details> tag is neat

**Comment by maxglycine** [comment]
I reviewed Steven's version and it is OK.  Should this pull request be cancelled?

**Comment by StevenCannon-USDA** [comment]
> I reviewed Steven's version and it is OK. Should this pull request be cancelled?

I think it would be marginally preferable for @Cheehau0659 to pull the contents of my version of the index.html into his (maybe manually; just copy-paste). Then one of us will approve and merge this revised PR. The original work was Chee Hau's, and having him review and incorporate the changes will be good pedagogically.

... However, this PR should be finished soon. @Cheehau0659 - please let us know if you expect NOT to be able to finish this by Oct 18.

**Comment by nathanweeks** [comment]
To allow scaling the use of iframes to the ontology conversion table as well, a further simplification could be usedl: if the _layouts/iframe.html is modified to also allow a URL pathname suffix to be appended to the "base" iframe URL, then a single HTML file with an appropriate iframe_url could be used to represent all (?) amigo URLs, obviating the need for a separate HTML page for each separate iframe URL.

The following example shows how this might be done (via a "iframe_pathname_suffix" URL parameter, which is used to construct the full iframe URL pathname, but removed from the list of query parameters passed to the iframe), and illustrated for a single URL:

```
--- a/_layouts/iframe.html
+++ b/_layouts/iframe.html
@@ -15,8 +15,11 @@
 <iframe id="myiframe" src="{{ page.iframe_url }}" style="{{ iframe_style }}"></iframe>
 
 <script language="javascript">
+    var params = new URL(window.location).searchParams;
+    var iframe_pathname_suffix = params.get("iframe_pathname_suffix") || '';
+    params.delete("iframe_pathname_suffix");
     var iframe = document.getElementById('myiframe');
-        iframe.src = iframe.src + window.location.search;
+        iframe.src = iframe.src + iframe_pathname_suffix + window.location.search;
 </script>
 
 </body>
--- /dev/null
+++ b/tools/ontology/amigo.html
@@ -0,0 +1,5 @@
+---
+layout: iframe
+iframe_url: "https://amigo.soybase.org/amigo/amigo/"
+---
+
--- a/tools/ontology/index.html
+++ b/tools/ontology/index.html
@@ -257,7 +257,7 @@ tools_menu: true
                   onclick="structureClose()">Close ...</a>
               </div>
               <br><br>
-              <button onclick="window.open('https://amigo.soybase.org/amigo/amigo/term/SOY:0000098','_blank');">Browse and Search Soybean Structure Terms</button>
+              <a href="/tools/ontology/amigo.html?iframe_pathname_suffix=/term/SOY:0000098">Browse and Search Soybean Structure Terms</a>
             </fieldset>
           </div>
         </td>
```

**Comment by StevenCannon-USDA** [comment]
Thanks for the changes, @Cheehau0659 . I additionally made the iframe simplifications that @nathanweeks suggested. I'll approve and merge this branch.

**Review by StevenCannon-USDA — APPROVED** [review]
Thanks for the changes, @Cheehau0659 . I additionally made the iframe simplifications that @nathanweeks suggested. I'll approve and merge this branch.

**Pull request merged**
