### PR TITLE
Add CMap classic (in iframe)

### PR DESCRIPTION
**Pull request by StevenCannon-USDA**
Many changes under maps/ to add CMap-classic within an iframe, and renaming the other CMap-js instances as cmapjs to distinguish from classic

### CODE REVIEW

**Comment by StevenCannon-USDA** [comment]
@nathanweeks @jd-campbell @maxglycine - Because of the large number of files that changed in this branch (114), I would like to get this merged into main soon, to avoid merge conflicts in other branches. Can one of you review today and either request changes or approve and merge?

**Comment by nathanweeks** [comment]
The CMap-classic links LGTM. To make CMap-js more similar to classic (where the backbones are in the middle & QTL on the either side), I'll suggest updating the position of the QTL tracks in the gm_gwas maps, changing `"position": -1` to `"position": 1` so the QTL tracks appear on the right-hand side of the backbone (and so the feature correspondence lines don't travel across the entire gm_gwas map area)

**Review by jd-campbell — CHANGES_REQUESTED** [review]
When clicking on the links on the map that is within the iframe I noticed that all the links provided in the popup box will be broken once the officially roll over to jekyll site is completed next month. Because the links are missing the "legacy" in front of soybase. Please see the screen below for reference. 
Screenshot 2024-08-31 at 15 57 00

**Comment by nathanweeks** [comment]
legacy links updated to use the "legacy" subdomain

**Comment by StevenCannon-USDA** [comment]
Thanks, @jd-campbell and @nathanweeks. Those suggested changes have been made (thanks for changing the links to legacy.soybase.org, Nathan).

**Review by jd-campbell — APPROVED** [review]
Looks good to me. Thank you @StevenCannon-USDA @weihuang12 and @nathanweeks for working on this.

**Pull request merged**
