### PR TITLE
Updated web components and added limiting gene search to "Glycine"

### PR DESCRIPTION
**Pull request by That-Thing**
Since it doesn't seem like any new changes are going to be made to the gene search, I updated the LIS web components to their current version from main, which supports limiting gene search by genus.
I also added the limiting parameter in the gene search in `tools/search/gene.html`

### CODE REVIEW

**Review by StevenCannon-USDA — COMMENTED** [review]
It looks good to me, and I see that the change is small on the Jekyll side, but it seems that the linkout service isn't functioning. I suspect that is a separate issue, but I'll ask about it before approving this PR.

**Comment by nathanweeks** [comment]
Since the theme uses a CDN for the web components instead of bundling the minified JS asset (https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/26), could this PR be modified to do the same, for provenance & easier upgrading?

**Comment by That-Thing** [comment]
It could, but the limiting parameter would break since it's not included in the 1.0.0 release.

**Comment by nathanweeks** [comment]
> It could, but the limiting parameter would break since it's not included in the 1.0.0 release.

Gotcha. If the resolution of https://github.com/legumeinfo/web-components/issues/218 looks imminent, this could perhaps wait until then. Otherwise, If it's anticipated that a pre-release version of the web-components might be needed now and in the future, perhaps it could be added to the repo as a git submodule & built via automated process (rather than adding/updating a manually-built artifact to the repo)?

**Comment by That-Thing** [comment]
That could be done, but adding in the components hosted on the CDN might be a better idea for right now since the new version of components should (hopefully) be released soon.

**Comment by alancleary** [comment]
> > It could, but the limiting parameter would break since it's not included in the 1.0.0 release.
> 
> Gotcha. If the resolution of [legumeinfo/web-components#218](https://github.com/legumeinfo/web-components/issues/218) looks imminent, this could perhaps wait until then. Otherwise, If it's anticipated that a pre-release version of the web-components might be needed now and in the future, perhaps it could be added to the repo as a git submodule & built via automated process (rather than adding/updating a manually-built artifact to the repo)?

Hey there. The 1.1.0 release is definitely the issue here. I'm going to try and have it done by the end of today. In the future please let me know if a release needs to happen. More generally I need to get a release cadence in place so that new content makes it into production in a timely manner.

**Comment by alancleary** [comment]
Just wanted to explicitly follow-up and say that v1.1.0 of the @legumeinfo/web-components NPM package has been released. There appears to be an unrelated issue in the jekyll-starter-legumeinfo repo that's preventing me from updating the web components version but you can manually update by adding `web_components_version: 1.1.0` to your `_config.yml` file.

**Comment by StevenCannon-USDA** [comment]
@That-Thing - Is this ready for re-review? I saw the changes earlier this week. At least in my instance, the Gene search page seems not to be functional, giving a "Failed to load data" message in the rendered page.

**Comment by That-Thing** [comment]
I'm still working on the linkouts, but the search itself should work fine.

**Comment by That-Thing** [comment]
It seems that the LIS GraphQL service is down right now, so that's why it might not be working on your end.

**Comment by StevenCannon-USDA** [comment]
@That-Thing - Ah, good. Thanks for confirming.
I see that the gene search is failing at legumeinfo as well. Pinging @alancleary in case there isn't a "watcher" on the GraphQL service.

**Comment by alancleary** [comment]
> @That-Thing - Ah, good. Thanks for confirming. I see that the gene search is failing at legumeinfo as well. Pinging @alancleary in case there isn't a "watcher" on the GraphQL service.

I'm not responsible for GraphQL deployment. I believe @adf-ncgr has taken on that responsibility.

**Comment by adf-ncgr** [comment]
not sure I have grasped the whole context, but it looks like the graphql server died with the following error:
```
graphql-server-110-graphql-server-1  | /app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:95
graphql-server-110-graphql-server-1  |         return new graphql_1.GraphQLError(`${response.status}: ${response.statusText}`, {
graphql-server-110-graphql-server-1  |                ^
graphql-server-110-graphql-server-1  |
graphql-server-110-graphql-server-1  | GraphQLError: 404: 404
graphql-server-110-graphql-server-1  |     at IntermineAPI.errorFromResponse (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:95:16)
graphql-server-110-graphql-server-1  |     at IntermineAPI.throwIfResponseIsError (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:87:26)
graphql-server-110-graphql-server-1  |     at /app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:199:32
graphql-server-110-graphql-server-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
graphql-server-110-graphql-server-1  |     at async IntermineAPI.fetch (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:231:56)
graphql-server-110-graphql-server-1  |     at async IntermineAPI.get (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:111:17)
graphql-server-110-graphql-server-1  |     at async IntermineAPI.webProperties (file:///app/dist/data-sources/intermine/intermine.server.js:54:16)
graphql-server-110-graphql-server-1  |     at async IntermineAPI.verifyIntermineVersion (file:///app/dist/data-sources/intermine/api/index.js:265:32) {
graphql-server-110-graphql-server-1  |   path: undefined,
graphql-server-110-graphql-server-1  |   locations: undefined,
graphql-server-110-graphql-server-1  |   extensions: {
graphql-server-110-graphql-server-1  |     response: {
graphql-server-110-graphql-server-1  |       url: 'https://mines.legumeinfo.org/legumemine/service/web-properties?format=json',
graphql-server-110-graphql-server-1  |       status: 404,
graphql-server-110-graphql-server-1  |       statusText: '404',
graphql-server-110-graphql-server-1  |       body: '<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;legumemine&#47;service&#47;web-properties] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.80</h3></body></html>'
graphql-server-110-graphql-server-1  |     }
graphql-server-110-graphql-server-1  |   }
graphql-server-110-graphql-server-1  | }
graphql-server-110-graphql-server-1  |
graphql-server-110-graphql-server-1  | Node.js v20.9.0
```
I'll try to prop it back up, but we may need to look further into what's causing this

**Comment by adf-ncgr** [comment]
has been restarted, gene search at legumeinfo.org seems to be working. let me know if you see other issues (or the same one again)

**Comment by alancleary** [comment]
Weird. It's probably worth bringing in @sammyjava on this. The web-properties URL is pinged constantly so if it going offline is going to bring down the server then that's a problem.

**Comment by adf-ncgr** [comment]
I'll start a new issue for it over on the graphql-server repos

**Comment by That-Thing** [comment]
Fixed the linkouts, everything should work as expected now.

**Review by StevenCannon-USDA — APPROVED** [review]
Looks good! Approving and will merge to main.

**Pull request merged**
